#!/usr/bin/env python
"""Build remaining seed JSON files (CCE cases, guidelines, resources, rapid sheets, schedule)."""
import json, pathlib

D = pathlib.Path(r"C:\Users\Kang\racgp-study-app\seed\data")

cce = [
 dict(title="Angry patient - delayed referral", category="Difficult consultation",
  testing="Professionalism, conflict de-escalation, maintaining a safe therapeutic relationship while addressing the complaint; complaints handling.",
  must_hits="Acknowledge and legitimise the frustration without becoming defensive; apologise for the experience ('I am sorry this has been stressful'); stay calm and non-defensive; find out what happened from the patient's view; identify what they want to happen now; offer clear next steps with a timeframe; offer a follow-up appointment; mention practice complaints process if unresolved.",
  traps="Becoming defensive or justifying the system; matching the patient's anger; dismissing the complaint; immediately blaming the specialist/hospital; over-promising; failing to acknowledge emotion before problem-solving.",
  structure="Opening: acknowledge early ('I can see this has been really frustrating'). Information gathering: open questions about timeline and impact; screen for clinical harm (did they miss treatment windows?). Explanation: honest account of what you can and cannot control. Management: concrete plan with timeframe. Closure: check understanding, thank them for raising it, arrange review.",
  phrases="'That sounds genuinely frustrating and I want to understand exactly what happened.' / 'I am sorry you have had this experience.' / 'What would a good outcome look like for you from here?' / 'Here is what I can do this week, and here is what I will find out and get back to you about by Friday.'",
  scoring="Examiner marks cluster around: empathy without defensiveness, taking ownership of a system failure, converting anger into a concrete plan, safe clinical review of the underlying condition."),
 dict(title="Demanding antibiotics for a viral URTI", category="Difficult consultation",
  testing="Antimicrobial stewardship communication, shared decision making, holding a safe line under pressure without damaging the relationship.",
  must_hits="Explore ICE (ideas, concerns, expectations) - why antibiotics, what do they fear (missing work, complications, child care); acknowledge the misery of the illness; give a clear diagnosis and explanation of viral vs bacterial; explain antibiotic harms (side effects, resistance, gut effects); offer a serious alternative plan: symptom relief, safety-netting, a script to use only if deteriorating (delayed prescribing where appropriate); check understanding.",
  traps="Prescribing to end the consultation; lecturing; dismissing expectations without exploring them; vague safety-netting; not offering alternatives.",
  structure="Opening: agenda. Information gathering: ICE + focused history. Explanation: name the diagnosis (viral URTI/bronchitis), explain natural history timeline. Management: symptom relief options, delayed prescription, what to watch for. Closure: check questions, confirm the plan is acceptable.",
  phrases="'Can I ask what you know about why this keeps happening?' / 'Most people find the cough lasts up to three weeks and that is normal - what would make you want to be seen again?' / 'There is a real chance this medicine would give you diarrhoea and no benefit.'",
  scoring="Marks for: exploring expectations before refusing; framing antibiotic harms concretely; delayed prescribing as a middle path; explicit safety-netting; maintaining alliance."),
 dict(title="Opioid request from a patient on repeat oxycodone", category="Difficult consultation",
  testing="Chronic pain management, safe opioid prescribing, boundary setting with empathy, dependence recognition.",
  must_hits="Full pain assessment (site, character, function, flare pattern); assess for opioid misuse red flags (early scripts, lost scripts, multiple prescribers); review PDMP/script history where available; assess function not just pain scores; explain the plan: not increasing the dose; offer a pain management review (multidisciplinary, physio, psychologist-lead pain program); consider opioid tapering discussion; safety-netting for dependence; involve a drug and alcohol service if dependence signs; document.",
  traps="Increasing the dose to end the consultation; framing the patient as drug-seeking without assessment; abrupt cessation without support; missing dependence signs; failing to offer alternatives; being judgemental.",
  structure="Opening: confirm the agenda (pain review + script request). Information gathering: pain story, function, sleep, mood, medication use pattern. Explanation: findings, risks of escalating doses at current levels. Management: structured plan, review interval, alternatives, what you will and will not do. Closure: written plan, follow-up date.",
  phrases="'Tell me what a good day and a bad day look like now.' / 'I want to help your pain, and increasing this medicine will not do that - it will change your risk of harm.' / 'Let us get you into the pain program and review this together in two weeks.'",
  scoring="Marks for: assessing before deciding; clear boundary with reason; offering real alternatives; dependence awareness; structured follow-up."),
 dict(title="Vaccine hesitancy in a parent", category="Preventive medicine",
  testing="Risk communication, addressing misinformation, maintaining the relationship, child protection awareness.",
  must_hits="Non-judgemental exploration of specific concerns (which vaccine, what feared outcome, information source); correct the specific misconception with plain-language evidence (address autism myth directly if raised); strong clear recommendation (vaccination is safe and recommended); avoid dismissing; leave the door open; address the schedule; document the discussion; safety-netting if unimmunised.",
  traps="Dismissiveness ('the science is settled'); overwhelming with data; ignoring the specific fear; ultimatums; failing to give a clear recommendation; not offering another appointment.",
  structure="Opening: rapport. Information gathering: specific concerns. Explanation: address each concern directly; acknowledge uncertainty honestly where it exists (rare adverse events). Management: recommendation + plan; offer follow-up conversation. Closure: warm, non-conditional relationship regardless of decision today.",
  phrases="'What have you read or heard that worries you most?' / 'The measles vaccine is about 97% effective at preventing measles, and the risk of a serious reaction to the vaccine itself is far smaller than the risks of measles.' / 'I am happy to talk more about this any time - my advice is to go ahead.'",
  scoring="Marks for: exploring the specific concern; a clear personal recommendation; not burning the relationship; a concrete plan for catch-up or follow-up."),
 dict(title="Abnormal result delivery - high PSA", category="Results and safety",
  testing="Breaking news, risk communication, safety-netting, arranging clear follow-up, managing patient anxiety.",
  must_hits="Prepare the setting; warn (a shot across the bow: 'I need to talk about a test result that needs more checking'); give the result in plain terms; pause and respond to emotion before details; explain what it may and may not mean (PSA is not a cancer diagnosis); explain the next steps (repeat test, examination, referral pathway, timeframes); check understanding; arrange a definite follow-up point (date, who, where); written information.",
  traps="Cavalier delivery without warning; drowning in statistics before acknowledging emotion; vague 'come back if worried' without a scheduled review; over-diagnosing ('you have cancer'); no written plan.",
  structure="Opening: agenda + warning shot. Delivery: the headline result in one sentence. Pause: acknowledge and address the emotional response. Explanation: what this might mean, differential. Management: investigations, referrals and timeframes. Closure: summarise, check questions, next appointment.",
  phrases="'I need to talk with you about a test result today - is now still a good time?' / 'The test is abnormal, and it does not mean you have cancer - it means we need more tests to be sure.' / 'Here is the plan and here is the date we will know more.'",
  scoring="Marks for: warning before delivering; chunking; tolerance of silence; concrete timeframe; explicit safety-netting; checking understanding."),
 dict(title="Cancer diagnosis consultation", category="Difficult consultation",
  testing="Breaking bad news (SPIKES framework), emotional responsiveness, information structuring, appropriate GP role in the cancer pathway.",
  must_hits="Setting (private, uninterrupted, support person offered); perception ('what do you know so far'); invitation ('how much detail would you like'); knowledge - warn then deliver the diagnosis in plain language; pause and acknowledge emotion (name it: 'I can see this is a shock'); strategy - treatment pathway, referral, timeframe; safety-netting (symptoms to report); offer a follow-up appointment; offer written information.",
  traps="Delivering the diagnosis without a warning shot; rushing past emotion to logistics; excluding the support person; drowning in staging detail; not offering a next GP contact point.",
  structure="SPIKES with GP flavour: Setting, Perception, Invitation, Knowledge, Emotions, Strategy and Summary.",
  phrases="'Are you happy for me to go through everything now, or would you rather take it step by step?' / 'I am sorry - it is cancer.' (pause, let silence work) / 'You will not be navigating this alone - here is exactly what happens next.'",
  scoring="Marks for: following a recognisable breaking-bad-news structure; genuine emotional handling; clear timeframe; explicit GP continuity role."),
 dict(title="Domestic violence disclosure", category="Safety and ethics",
  testing="Safety assessment, confidentiality, validated screening approach, response to disclosure, knowledge of legal duties.",
  must_hits="Private enquiry (never with partner or children present); direct, normalising question; believe and validate ('this is not your fault'); immediate safety assessment: recent escalation, threats to kill, strangulation, weapons, children's safety; risk of harm assessment; give information (1800RESPECT, DV connect) without writing it down if unsafe at home; patient-led decision making - do not force leaving; child protection assessment (QLD: witnessing FDV is a reportable harm); document carefully (legible, factual, time-stamped - records can support DVO applications); safety-planning; arrange follow-up.",
  traps="Asking with the partner present; giving advice to leave immediately (peak danger time); breaking confidentiality by involving police without consent (unless imminent risk to life/child safety); failing to assess children; writing information on paper the partner may find.",
  structure="Opening: alone, confidentially. Information gathering: violence pattern, safety, children. Explanation: it is not your fault; there are services. Management: safety plan, referrals, documentation, child assessment. Closure: follow-up plan.",
  phrases="'Can I ask you a few personal questions? Everything here is confidential.' / 'Nothing you have told me changes my respect for you.' / 'Is it safe for you to go home tonight?' / 'If you ever need it, this number can be called from a locked phone.'",
  scoring="Marks for: privacy ensured; direct questioning; validation; children assessed; safety planning; documentation; patient-led pace."),
 dict(title="Adolescent confidentiality - contraception at 15", category="Ethics and law",
  testing="Gillick competence assessment, confidentiality and its limits, adolescent-friendly consultation, mandatory reporting awareness.",
  must_hits="See the patient alone (explain why to both parent and teen); assess Gillick competence explicitly (understands treatment, benefits, risks, alternatives, consequences of refusing); confidentiality and its limits up-front (will break it if risk of serious harm to self or others); TAKE history (Time alone, Attention, Kick out parents/guardian, Establish confidentiality); contraception discussion; STI screening; mandatory reporting: sexual activity under 16 requires consideration of reportable concerns in most jurisdictions (consent laws vary by state) - know QLD rules; document.",
  traps="Refusing contraception outright because of age; breaking confidentiality to parents without cause; failing to consider mandatory reporting when the partner is older; lecturing; not assessing coercion/exploitation.",
  structure="Opening: contract for confidentiality. Information gathering: HEADSS assessment. Clinical: contraception + STI + safety. Legal: competence + reporting considerations. Closure: plan, follow-up, crisis contacts.",
  phrases="'Whatever we discuss stays between us unless I think you or someone else is at serious risk.' / 'Can I check what you already know about how this works?' / 'Everything you tell me helps me look after you better.'",
  scoring="Marks for: seeing alone; explicit competence assessment; stating confidentiality limits; considering reporting duties; non-judgemental rapport."),
 dict(title="Child protection concern - suspicious injury", category="Safety and ethics",
  testing="Recognising abuse patterns, mandatory reporting obligations (QLD), handling the consultation, documentation.",
  must_hits="Recognise inconsistent injury/history (story does not fit the injury, delay in presentation, changing accounts); pattern injuries; do NOT confront or accuse the caregiver in the room; complete a full head-to-toe examination when safe; document verbatim quotes, body maps; understand QLD mandatory reporting: report to Child Safety (QLD) if you suspect a child has suffered, is suffering, or is at risk of significant harm - GP reporting is mandatory under legislation; consult paediatrics/child protection unit if unsure; safety-netting the child's immediate situation; do not let the child leave if imminent danger (call police if needed).",
  traps="Confronting the parent (child may be put at further risk); waiting for certainty before reporting (the threshold is reasonable suspicion, not proof); poor documentation (he said/she said without quotes); not reporting because social work 'might not do anything'; missing siblings' safety.",
  structure="Information gathering: history verbatim, inconsistencies noted gently. Examination: complete, documented. Decision: reporting threshold. Action: report, consult, safety plan. Documentation: exact quotes, timing, who was present.",
  phrases="'Can you help me understand how this happened - tell me about that day from the beginning.' / 'I need to make sure Tom is safe - I am going to talk with the child protection team who help us with this.'",
  scoring="Marks for: pattern recognition; threshold understanding (reasonable suspicion); not confronting; verbatim documentation; correct QLD pathway."),
 dict(title="Elderly patient with cognitive decline + driving", category="Older persons",
  testing="Capacity vs cognitive impairment, fitness-to-drive legal duties, balancing autonomy and safety, family dynamics.",
  must_hits="Differentiate dementia vs delirium vs depression; objective cognitive testing plus functional assessment (finance, meds, cooking); ask about driving directly and assess insight; legal duty: conditions likely to affect safe driving must be reported to the licensing authority (Austroads; QLD: Qld Transport) - both patient duty to notify and practitioner reporting pathway; discuss transport alternatives and the identity/financial impacts of losing the licence; involve family with consent; safety-net for getting lost, fires, financial abuse; RACF/GP management plan options.",
  traps="Ignoring the driving issue because it is awkward; assuming capacity is absent because of the diagnosis; breaching confidentiality by reporting without discussing first where safe; focusing only on cognition score rather than function.",
  structure="Information gathering: cognition + function + driving + insight + supports. Explanation: what is happening to memory, what must legally happen about driving. Management: reporting process with patient, alternatives, supports, safety. Closure: follow-up, family meeting.",
  phrases="'How have you been finding the driving lately - any close calls?' / 'The law says doctors must let the transport authority know about conditions that affect safe driving - I want us to do this together properly.' / 'Losing the licence is a huge life change - let us plan how you keep your independence.'",
  scoring="Marks for: recognising the legal reporting duty; assessing insight; patient-first process; planning alternatives; distinguishing dementia/delirium/depression."),
 dict(title="Capacity assessment - refusing a needed operation", category="Ethics and law",
  testing="Capacity assessment structure, four-component test, autonomy, escalation when capacity is impaired.",
  must_hits="Capacity is decision-specific and time-specific; assess for THIS decision; four abilities: understand the information, retain it, weigh it, communicate the choice; use a structured tool where needed; look for reversible causes (delirium, infection, depression); ensure information is given in the best way (interpreter, simple language) BEFORE declaring incapacity; if capacity present: respect the refusal and document; if absent: substitute decision-maker hierarchy (QLD), emergency doctrine for urgent; second opinion for significant decisions; document the assessment itself.",
  traps="Using MMSE as a capacity test; assuming a 'bad' decision means no capacity; not treating reversible delirium first; skipping the attempt at supported communication; not documenting the assessment process.",
  structure="Information gathering: cognition, delirium screen, mental state. Assessment: the four abilities with the actual decision. Outcome: capacity/no capacity; decision pathway. Documentation and follow-up.",
  phrases="'I want to make sure this decision is truly yours - let me go through it again and check what matters most to you.' / 'You have the right to refuse this operation, even if I think it is a mistake - my job is to make sure you have all the facts.'",
  scoring="Marks for: decision-specific framing; four-abilities structure; reversible causes; correct pathway if impaired; documentation."),
 dict(title="Medication error disclosure", category="Professionalism and safety",
  testing="Open disclosure, duty of candour, incident management, clinical governance, apology without admission of legal liability (per open disclosure framework).",
  must_hits="Recognise the error and its clinical impact; prioritise clinical safety of the patient first (assess harm, treat); open disclosure: honest timely communication of what happened; apologise for the harm ('I am sorry this happened to you') - express regret for the outcome; explain what happened and what will be done; avoid speculation and blame of colleagues; report through the practice incident system; reflect on prevention (system change); document the conversation; offer follow-up and questions; support for the doctor involved (doctors' health).",
  traps="Concealment or minimising; blaming a colleague or the system ('the nurse's fault'); promising no consequences; legalese refusal to discuss; failing to treat the clinical consequences first.",
  structure="Immediate: clinical assessment of the patient. Then: open disclosure conversation. Then: incident report, practice learning, documentation, follow-up.",
  phrases="'I need to tell you about something that should not have happened.' / 'I am sorry - this should not have happened, and here is what we are doing about it now.' / 'Here is how we will prevent this happening to someone else.'",
  scoring="Marks for: clinical safety first; genuine apology for harm; no blame-shifting; incident reporting; prevention thinking; documentation."),
 dict(title="Colleague impairment concern", category="Professionalism and safety",
  testing="Professional obligation to protect patients, doctors' health pathways, non-judgemental handling, escalation ladder.",
  must_hits="Obligation: patient safety comes first - you cannot ignore impairment concerns; approach the colleague directly with concern (health and behaviour observations only, not accusations); strongly encourage the doctor to contact the doctors' health service (QLD Doctors' Health Programme) or their own GP; escalate: if they refuse and risk persists - notify the practice principal, Medical Board (mandatory notification for impairment risk, intoxication while practising, or significant departure from standards - 'mandatory notification' applies to treating practitioners rarely but colleagues have an obligation); not anonymous gossip; documentation.",
  traps="Doing nothing; diagnosing the colleague; going straight to AHPRA without addressing first where safe; gossiping with other staff; taking over their patient load without addressing the cause.",
  structure="Observation: specific, factual concerns. Conversation: concerned, private, supportive. Pathway: own GP / Doctors' Health. Escalation: if refusal + risk. Documentation.",
  phrases="'I am worried about you - I have noticed X, and I would want someone to say it to me. Can I help you get some support?' / 'My first obligation is to patients - I cannot un-see this if nothing changes.'",
  scoring="Marks for: patient-safety-first framing; direct supportive approach; knowing doctors' health services; knowing the escalation duty; avoiding diagnosis/gossip."),
 dict(title="Cultural safety - Aboriginal or Torres Strait Islander patient", category="Cultural safety",
  testing="Cultural safety (not mere awareness), communication, health system navigation, CTG PBS/close the gap items, racism-aware practice.",
  must_hits="Ask (don't assume) how the patient identifies and what they prefer ('do you identify as Aboriginal or Torres Strait Islander?') - asking respectfully supports access to CTG benefits; build understanding of family/community context for decisions; check preferred way of receiving information; use interpreters when needed (Torres Strait Creole etc); offer/flag 715 health check and CTG PBS prescriptions; acknowledge Country where appropriate to the practice context; be aware of institutional barriers past and present (Stolen Generations, stolen wages) and their effect on trust; refer to Aboriginal Community Controlled Health Organisations where the patient prefers; do not treat the person as a spokesperson for their community.",
  traps="Assuming identification from appearance; ignoring CTG entitlements; cultural 'competence' performance (tokenism); treating culture as a checklist; missing specific clinical risks (e.g. CVD risk assessment from age 30).",
  structure="Opening: rapport, ask about preferences. Information gathering: family, community, social circumstances, holistic health. Clinical: high-priority conditions (diabetes, CVD from 30, kidney). Management: 715 check, CTG scripts, preferred services. Closure: clear follow-up.",
  phrases="'Can I ask - do you identify as Aboriginal or Torres Strait Islander? It helps me make sure you get everything you are entitled to.' / 'Who else in your family would you like involved in these decisions?'",
  scoring="Marks for: respectful enquiry; CTG items knowledge; family/community context; avoiding stereotypes; genuine two-way communication."),
 dict(title="Interpreter use with a newly arrived patient", category="Migrant and refugee health",
  testing="Working with interpreters, health literacy, refugee health basics, cost barriers, Medicare access.",
  must_hits="Book a professional interpreter (TIS National - free for GPs for Medicare-eligible patients; document language and dialect); speak to the patient, not the interpreter; short sentences, one idea at a time; teach-back to confirm understanding; be alert to refugee health issues (torture/trauma awareness - do not force disclosure; screening for TB, hepatitis B, parasites, vitamin D, iron); check Medicare/visa status implications for care; cultural mediators where needed; written information in language where possible.",
  traps="Using family members (especially children) as interpreters - breaches confidentiality and accuracy; speaking to the interpreter instead of the patient; assuming English proficiency from a few phrases; missing health-care-access barriers (cost, transport, visa); over-focusing on exotic disease and missing common problems.",
  structure="Opening: introduce via interpreter, confirm language/dialect. Information gathering: presenting complaint + targeted refugee screen when appropriate/consented. Explanation: teach-back. Management: access arrangements, interpreters for future visits. Closure: confirm plan in-language.",
  phrases="'I will get an interpreter so we can be sure we understand each other properly.' / 'Just so I know I explained it well - can you tell me in your own words what we will do?'",
  scoring="Marks for: professional interpreter; direct address; teach-back; refugee health awareness; access solutions."),
 dict(title="Suicidal patient consultation", category="Mental health",
  testing="Risk assessment depth, safety planning, escalation, documentation, GP confidence with psychiatric emergencies.",
  must_hits="Direct, calm questioning: thoughts, plan, means access, intent, timeframe, past attempts, substances; risk formulation: acute vs chronic risk; protective factors; means restriction (medication supply, weapons); safety plan (warning signs, coping steps, who to contact, crisis lines); involve supports with consent; decide: community management vs urgent psychiatric assessment vs ED; know when to use the Mental Health Act; document the assessment and plan; follow-up arranged (within days, not weeks); give written crisis numbers.",
  traps="Relying on 'no-suicide contracts'; asking only 'are you thinking of harming yourself?' without plan/means/intent; missing intoxication; prescribing lethal quantities without a plan; vague 'come back next week'.",
  structure="Opening: direct, unhurried. Assessment: thoughts/plan/means/intent/timeline, past history, substances, protective factors. Formulation: level of risk. Management: safety plan, means restriction, supports, follow-up, escalation if needed. Documentation.",
  phrases="'When you say you do not want to wake up - do you have thoughts of ending your life?' / 'Have you thought about how you would do it? Do you have access to that?' / 'Here is our plan if things get worse this week - who will you call first?'",
  scoring="Marks for: depth and directness of assessment; means restriction; safety planning (not contracts); appropriate escalation; concrete follow-up."),
 dict(title="Chronic disease review - GP chronic disease management", category="Chronic disease",
  testing="Structured chronic disease review, GP management plan items (MBS 721/723/725 for chronic condition + complex), team care coordination, self-management support, multimorbidity prioritisation.",
  must_hits="Structured review of each condition (T2DM, HTN, lipids) with targets reviewed; lifestyle as foundation (exercise, diet, smoking, alcohol); medication review and simplification; complication screening (eyes, feet, kidneys - the annual cycle); GP management plan + team care arrangements when eligible (MBS items); self-management goals with the patient (SMART goals); prioritise what matters most to the patient where multimorbidity competes; coordinate team (dietitian, diabetes educator, podiatry); follow-up interval clear.",
  traps="Glycaemic tunnel vision (ignoring BP/lipids/smoking which often kill more); prescribing without review; not using MBS items to fund team care; excluding the patient from priorities; vague lifestyle advice ('eat better, move more').",
  structure="Opening: agenda + what matters to the patient. Assessment: targets, complications, function. Management: medication changes, team care, plan items, self-management goals. Closure: written plan, next review.",
  phrases="'Of everything we manage today - what matters most to you?' / 'Your blood pressure is what lowers your risk of stroke most - let us start there.' / 'I will organise the plan that lets the dietitian and diabetes educator be bulk-billed for you.'",
  scoring="Marks for: structured comprehensive review; multimorbidity prioritisation; team coordination; patient-centred goals; MBS item knowledge."),
 dict(title="Perimenopause symptom counselling", category="Women's health",
  testing="Menopause management, MHT risk-benefit communication, individualised care, lifestyle, non-hormonal options.",
  must_hits="Symptom assessment (VMS, sleep, mood, GSM); frame menopause as normal life stage with a treatment decision, not a disease; MHT: most effective for VMS; discuss type (oestrogen + progestogen if uterus intact), timing hypothesis (start <60y or within 10 years of menopause for favourable risk-benefit), contraindications (hormone-dependent cancer, VTE history, CVD risks); non-hormonal options (SSRIs/SNRIs, clonidine, gabapentin); vaginal oestrogen for GSM (minimal systemic absorption, long-term ok); bone health; lifestyle (weight, exercise, alcohol, smoking); review plan.",
  traps="Either/or thinking (MHT or nothing); treating everyone with MHT; ignoring contraception in perimenopause (still needed 12 months post LMP or age 50-55 rules); forgetting GSM treatment; outdated absolute risk framing (WHI-era blanket fear).",
  structure="Opening: symptom inventory + goals. Information gathering: bleeding pattern, risk factors, family history. Explanation: what is happening; treatment options with risks/benefits. Management: shared decision - MHT type or alternatives, lifestyle. Closure: review in 6-8 weeks, when to report bleeding.",
  phrases="'There is no right answer for everyone - let us weigh your symptoms against your personal risks.' / 'The hottest data we have says starting MHT within 10 years of menopause has a favourable safety profile for most women.' / 'You still need contraception in perimenopause even if periods are irregular.'",
  scoring="Marks for: individualised risk-benefit framing; timing hypothesis knowledge; non-hormonal options; GSM addressed; contraception not forgotten."),
 dict(title="Pregnancy counselling - unintended pregnancy", category="Sexual and reproductive health",
  testing="Options counselling (parenting, adoption, termination), non-directiveness, legal knowledge (QLD termination to 22 weeks; >22 weeks specific criteria), signposting, contraception follow-through.",
  must_hits="Confirm pregnancy dating (dates, ultrasound); non-directive counselling: all three options (continue + parent, continue + adoption, termination) explored without steering; QLD law: termination available on request up to 22 weeks gestation; beyond 22 weeks requires two doctors agreeing specific grounds; provide referral information for whichever option chosen (termination services, antenatal care, perinatal mental health); discuss contraception plan regardless of choice; check for coercion (partner/family pressure either way); screen mental health; document; safety-net (ectopic symptoms).",
  traps="Directiveness (subtle or overt) toward any option; misinformation about termination legality; assuming the partner's view is hers; forgetting contraception and mental health; missing coercion.",
  structure="Opening: agenda + non-judgemental contract. Information gathering: circumstances, supports, coercion screen, health. Information: options with pathways and timeframes (time-critical). Decision: patient-led. Plan: referral, contraception, follow-up within days. Safety-net.",
  phrases="'There are three paths from here and I will walk any of them with you - what are you leaning toward?' / 'Whatever you choose, we will sort out contraception so this does not happen again unless you want it to.'",
  scoring="Marks for: genuine non-directiveness; accurate QLD law; time-sensitivity awareness; coercion screen; contraception and follow-up."),
 dict(title="Lifestyle counselling - motivational interviewing", category="Preventive medicine",
  testing="Brief behaviour-change intervention, motivational interviewing technique, avoiding the expert trap, SMART goals.",
  must_hits="Permission to discuss ('would it be ok if we talked about weight/smoking?'); explore importance ('why is this a 6 and not a 2 for you?'); explore confidence ('what would make it easier?'); reflective listening over advice-giving; elicit change talk; avoid the righting reflex; one behaviour at a time; SMART goal agreed; arrange follow-up; know pharmacotherapy/program options to offer when ready.",
  traps="The righting reflex (arguing for change); vague advice; targeting everything at once; judgement; no follow-up arranged.",
  structure="Opening: permission. MI: importance and confidence rulers, reflective listening. Planning: SMART goal, supports. Closure: follow-up date.",
  phrases="'Would you mind if we talked about your drinking today?' / 'You said it is a 6 - why a 6 and not a 2?' / 'What would need to be different for that to feel possible?'",
  scoring="Marks for: permission seeking; MI technique (rulers, reflections, change talk); one SMART goal; follow-up.")
]
(D / "cce_cases.json").write_text(json.dumps(cce, indent=1), encoding="utf-8")
print("CCE:", len(cce), "cases")

guidelines = [
 dict(tier=1, title="Guidelines for preventive activities in general practice (Red Book), 10th edition", publisher="RACGP", year="2024",
  url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/red-book",
  key_points="The reference for what to screen, when, and what NOT to screen. GRADE-based recommendations; expanded women's health across the reproductive lifespan.",
  thresholds="Cervical 25-74 5-yearly HPV; bowel 45-74 2-yearly iFOBT; breast 50-74 2-yearly (40+ eligible); BP checks at every visit; CVD risk 45-74 (30+ ATSI); T2DM screening by risk (every 3 years from 40, or 18 in high-risk groups).",
  exam_relevance="AKT asks screening intervals/thresholds directly; KFP builds screening-consultation cases; CCE uses screening conversations."),
 dict(tier=1, title="Australian Asthma Handbook", publisher="National Asthma Council Australia", year="Current (living)",
  url="https://www.nationalasthma.org.au/australian-asthma-handbook/complete-handbook",
  key_points="SABA-only treatment is out; ICS-formoterol reliever/maintenance (AIR) for most; assessment of severity/control; written action plans.",
  thresholds="Reliever use >2x/week = poor control; preventer indicated.",
  exam_relevance="Recurring AKT topic and common KFP scenario (the SABA-overuser)."),
 dict(tier=1, title="Therapeutic Guidelines (eTG complete)", publisher="Therapeutic Guidelines Ltd", year="Living/updated",
  url="https://tgldcdp-tg-org-au.ezproxy.library.uq.edu.au/ (or https://tg.org.au)",
  key_points="The antibiotic reference for Australian GP: first-line choices for common infections, durations, and allergy alternatives.",
  thresholds="Antibiotic choices, durations, and when not to treat.",
  exam_relevance="Directly examinable: first-line antibiotic choices for UTI, cellulitis, pneumonia, sore throat."),
 dict(tier=1, title="Australian Immunisation Handbook", publisher="Australian Government Dept Health / ATAGI", year="Living (major updates June 2026)",
  url="https://immunisationhandbook.health.gov.au/",
  key_points="21vPCV replaced 13vPCV/23vPPV in adult schedule (2026); RSV program expansion; MenB (with paracetamol prophylaxis); catch-up rules.",
  thresholds="NIP schedule ages; valid contraindications; minimum intervals.",
  exam_relevance="AKT favourite: schedule ages, contraindications, catch-up logic."),
 dict(tier=1, title="2023 Australian Guideline for assessing and managing cardiovascular disease risk", publisher="Heart Foundation", year="2023",
  url="https://www.heartfoundation.org.au/for-professionals/clinical-resources/cardiovascular-disease-risk-assessment",
  key_points="Absolute risk approach using Aus CVD Risk Calculator; assess from 45 (30 ATSI); statin decisions by risk band not LDL alone.",
  thresholds="Low <10%, moderate 10-15%, high >15% (5-year). High risk: treat. Diabetes >=50, established CVD, CKD, FH = treat regardless.",
  exam_relevance="Core AKT/KFP territory: who gets a statin."),
 dict(tier=1, title="Australian Clinical Guidelines for Diagnosis and Management of Atrial Fibrillation", publisher="Heart Foundation + CSANZ", year="2018 (current)",
  url="https://www.heartfoundation.org.au/for-professionals/clinical-resources/atrial-fibrillation-resources",
  key_points="CHA2DS2-VA (no sex category - Australian change); opportunistic screening pulse/ECG >65; rate vs rhythm.",
  thresholds="Anticoagulate CHA2DS2-VA >=2 (>=1 in some higher-risk contexts).",
  exam_relevance="AKT: anticoagulation threshold and DOAC choice; KFP: AF review cases."),
 dict(tier=1, title="COPD-X (Australian and New Zealand guidelines for COPD)", publisher="Lung Foundation Australia", year="Current",
  url="https://copdx.org.au/copd-x-plan/",
  key_points="Confirm with spirometry; smoking cessation changes trajectory; pulmonary rehab; inhaler step-up by exacerbations/eosinophils.",
  thresholds="Post-bronchodilator FEV1/FVC <0.7 = diagnosis; ICS if eos >=0.3 or >=2 exacerbations.",
  exam_relevance="AKT: step-up logic. KFP: the frequent exacerbator."),
 dict(tier=1, title="Australian STI Management Guidelines for Use in Primary Care", publisher="ASHM", year="Living",
  url="http://sti.guidelines.org.au/",
  key_points="Site-specific NAAT testing, first-line treatments (as per eTG align), partner notification duties.",
  thresholds="Screening intervals by risk; test of cure intervals.",
  exam_relevance="AKT: STI treatment choices; CCE: sexual history technique."),
 dict(tier=1, title="National Cervical Screening Program: Guidelines for the management of screen-detected abnormalities", publisher="Cancer Council Australia / Dept Health", year="2016 (updated Dec 2020; current)",
  url="https://screening.cancer.org.au/cervical/",
  key_points="HPV-based screening; self-collection equality; intermediate/higher-risk pathways; exit testing 70-74.",
  thresholds="25-74, 5-yearly; self-collected samples with HPV (not 16/18) require return for LBC.",
  exam_relevance="AKT: program intervals; KFP: the overdue/anxious screener."),
 dict(tier=2, title="Comprehensive Australian Clinical Guideline for ACS (2025)", publisher="Heart Foundation + CSANZ", year="2025",
  url="https://www.heartfoundation.org.au/for-professionals/clinical-resources/acute-coronary-syndromes",
  key_points="New 2025 guideline: ACS pathways, DAPT duration choices, secondary prevention bundle, DOAC+antiplatelet strategies in AF+ACS.",
  thresholds="DAPT duration by bleeding/ischaemic risk; step-down strategies.",
  exam_relevance="AKT: post-ACS medication bundles."),
 dict(tier=2, title="Guideline for diagnosis and management of hypertension in adults (2016)", publisher="Heart Foundation", year="2016 (2026 guideline in development - Q4 2026)",
  url="https://www.heartfoundation.org.au/for-professionals/clinical-resources/hypertension",
  key_points="Confirm before treating; out-of-office measurement; absolute risk context; new 2026 guideline due Q4 2026 - watch for changes.",
  thresholds="Diagnosis generally >=140/90 clinic confirmed; management by absolute risk.",
  exam_relevance="AKT: who to treat; KFP: white-coat scenario."),
 dict(tier=2, title="Australian guideline for MASLD (fatty liver)", publisher="Various (consensus-based)", year="2023-2025",
  url="",
  key_points="FIB-4 first-line fibrosis staging; 7-10% weight loss core therapy; cardiovascular risk is the main driver of mortality in MASLD.",
  thresholds="FIB-4 <1.3 low risk (age <65); elastography if intermediate.",
  exam_relevance="KFP: abnormal LFT cases; AKT: diagnosis pattern."),
 dict(tier=2, title="RACGP Silver Book - Medical care of older persons in residential aged care facilities", publisher="RACGP", year="Current edition",
  url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/silver-book",
  key_points="RACF-specific: advance care planning, deprescribing, falls, palliative, behaviour management (avoid chemical restraint).",
  thresholds="Frailty-aware targets; restrictive practice minimisation.",
  exam_relevance="CCE loves RACF scenarios; KFP older-person cases."),
 dict(tier=2, title="Austroads Assessing Fitness to Drive", publisher="Austroads", year="2024 (current)",
  url="https://austroads.com.au/drivers-and-vehicles/driver-health/assessing-fitness-to-drive",
  key_points="Standards for medical conditions and driving: dementia, epilepsy, diabetes, sleep apnoea, CVD, alcohol. Both patient and practitioner notification duties.",
  thresholds="Private vs commercial standards differ; e.g., diabetes on insulin: 5-yearly review.",
  exam_relevance="AKT/CCE: the driving conversation is high-yield CCE."),
 dict(tier=2, title="RANZCOG pregnancy care guidelines / antenatal care", publisher="RANZCOG / Dept Health", year="Current",
  url="https://www.health.gov.au/our-work/clinical-practice-guidelines-pregnancy-care",
  key_points="Antenatal visit schedule, screening tests each trimester, medication safety in pregnancy.",
  thresholds="First visit by 10-12 weeks; GTT 24-28 weeks; anti-D timings.",
  exam_relevance="AKT: antenatal schedule/test timing."),
 dict(tier=2, title="Type 2 diabetes management in general practice", publisher="RACGP/Diabetes Australia", year="2020 (update in development)",
  url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/type-2-diabetes",
  key_points="ADD-STEP comorbidity-based agent selection; annual cycle of care; individualised targets.",
  thresholds="HbA1c generally <=7%; retinal/foot/ACR annually.",
  exam_relevance="Core of multiple AKT questions and KFP reviews."),
 dict(tier=2, title="Kidney Health Australia - CKD management in primary care", publisher="Kidney Health Australia", year="Current",
  url="https://kidney.org.au/health-professionals/chronic-kidney-disease-management-in-primary-care",
  key_points="eGFR + ACR staging; RAAS blockade with albuminuria; SGLT2i; nephrology referral criteria.",
  thresholds="Refer if eGFR <30, ACR >60, rapid decline, or haematuria + proteinuria.",
  exam_relevance="KFP: CKD review case; AKT: referral thresholds."),
 dict(tier=2, title="Voluntary Assisted Dying (QLD)", publisher="Queensland Health", year="2023 (in force)",
  url="https://www.health.qld.gov.au/__data/assets/pdf_file/0032/1143366/vad-guidance-for-health-practitioners.pdf",
  key_points="VAD legal in QLD since Jan 2023: eligibility (adult, resident, decision-capable, intolerable suffering from advanced condition), first/second request process, coordinating practitioner role, conscientious objection rights for doctors.",
  thresholds="Eligibility is assessed - not all requests proceed; process is strictly legal.",
  exam_relevance="CCE ethics stations; AKT legal questions."),
 dict(tier=3, title="eTG Palliative Care / Therapeutic Guidelines Palliative Care", publisher="TG Ltd", year="Current",
  url="https://tg.org.au",
  key_points="Anticipatory prescribing sets, terminal care pathways, symptom algorithms.",
  thresholds="Dosing conversions opioid routes.",
  exam_relevance="KFP palliative cases; AKT symptom drug choices."),
 dict(tier=3, title="RCH Clinical Practice Guidelines (Paediatrics)", publisher="Royal Children's Hospital Melbourne", year="Living",
  url="https://www.rch.org.au/clinicalguide/",
  key_points="Practical paediatric protocols: fever, bronchiolitis, croup, gastro, asthma, head injury, analgesia dosing.",
  thresholds="Weight-based dosing; referral criteria.",
  exam_relevance="AKT paediatric dosing and criteria; KFP child cases."),
 dict(tier=3, title="RACGP Green Book - Putting prevention into practice", publisher="RACGP", year="Current",
  url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/green-book",
  key_points="How to build prevention into practice systems rather than individual willpower.",
  thresholds="Practice-level recall and reminder systems.",
  exam_relevance="Occasional AKT on practice systems."),
 dict(tier=3, title="White Book - Abuse and violence: working with our patients", publisher="RACGP", year="Current",
  url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/white-book",
  key_points="How to ask, respond, safety-assess, document, and refer for FDV; practice-level safety.",
  thresholds="Strangulation = high risk marker.",
  exam_relevance="CCE FDV station is common; KFP documentation/management questions."),
]
(D / "guidelines.json").write_text(json.dumps(guidelines, indent=1), encoding="utf-8")
print("Guidelines:", len(guidelines))

resources = [
 dict(domain="Preventive medicine / screening", primary_res="RACGP Red Book 10th ed (2024)", secondary_res="Health.gov.au program pages (cervical, bowel, breast)", rapid_review="Personal screening-intervals card", url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/red-book"),
 dict(domain="Cardiovascular disease", primary_res="2023 Australian CVD Risk guideline + Aus CVD Risk Calculator", secondary_res="eTG Cardiovascular", rapid_review="Risk-band statin table", url="https://www.heartfoundation.org.au/for-professionals/clinical-resources/cardiovascular-disease-risk-assessment"),
 dict(domain="Hypertension", primary_res="Heart Foundation HTN resources (2016 guideline; 2026 update pending Q4)", secondary_res="eTG", rapid_review="Confirm-then-treat flowchart", url="https://www.heartfoundation.org.au/for-professionals/clinical-resources/hypertension"),
 dict(domain="Atrial fibrillation", primary_res="Australian AF guideline (2018, current)", secondary_res="eTG Cardiovascular; ACS 2025 for AF+ACS combos", rapid_review="CHA2DS2-VA card", url="https://www.heartfoundation.org.au/for-professionals/clinical-resources/atrial-fibrillation-resources"),
 dict(domain="Asthma", primary_res="Australian Asthma Handbook", secondary_res="eTG Respiratory", rapid_review="AIR algorithm card", url="https://www.nationalasthma.org.au/australian-asthma-handbook/complete-handbook"),
 dict(domain="COPD", primary_res="COPD-X", secondary_res="Lung Foundation resources", rapid_review="Step-up logic card", url="https://copdx.org.au/copd-x-plan/"),
 dict(domain="Diabetes", primary_res="RACGP/Diabetes Australia T2DM guidelines", secondary_res="ADS (Australian Diabetes Society) position statements", rapid_review="Cycle-of-care card", url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/type-2-diabetes"),
 dict(domain="CKD", primary_res="Kidney Health Australia CKD in primary care", secondary_res="eTG Kidney", rapid_review="eGFR/ACR grid", url="https://kidney.org.au/health-professionals/chronic-kidney-disease-management-in-primary-care"),
 dict(domain="Immunisation", primary_res="Australian Immunisation Handbook (living)", secondary_res="NIP schedule PDF; ATAGI statements", rapid_review="NIP schedule card (update after each change!)", url="https://immunisationhandbook.health.gov.au/"),
 dict(domain="Infections/antibiotics", primary_res="eTG Antibiotic", secondary_res="Australian Commission on Safety and Quality - AURA", rapid_review="Top-20 antibiotic choices card", url="https://tg.org.au"),
 dict(domain="Mental health", primary_res="RACGP depression guidelines; beyondblue clinical practice", secondary_res="RANZCP clinical practice guidelines", rapid_review="K10/PHQ-9 + action card", url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/depression"),
 dict(domain="Suicide risk", primary_res="LIFE Framework; RACGP suicide prevention resources", secondary_res="QLD Mental Health Line protocols", rapid_review="Risk assessment template", url="https://lifeinmindaustralia.com.au"),
 dict(domain="Women's health - cervical", primary_res="NCSP guidelines (Cancer Council)", secondary_res="health.gov.au NCSP pages", rapid_review="Result-pathway flowchart", url="https://screening.cancer.org.au/cervical/"),
 dict(domain="Contraception", primary_res="FSRH/SHQ (QLD) resources; Mirena/insertion training", secondary_res="eTG Reproductive", rapid_review="UKMEC card", url="https://shq.org.au"),
 dict(domain="Menopause", primary_res="IMS/Australasian Menopause Society", secondary_res="Jean Hailes", rapid_review="MHT decision card", url="https://www.menopause.org.au"),
 dict(domain="Sexual health / STI", primary_res="Australian STI Management Guidelines", secondary_res="ASHM resources; QLD Sexual Health", rapid_review="Site-Test-Treat table", url="http://sti.guidelines.org.au/"),
 dict(domain="Pregnancy / antenatal", primary_res="Dept Health Clinical Practice Guidelines Pregnancy Care", secondary_res="RANZCOG C-Gen statements", rapid_review="Antenatal schedule card", url="https://www.health.gov.au/our-work/clinical-practice-guidelines-pregnancy-care"),
 dict(domain="Paediatrics", primary_res="RCH Clinical Practice Guidelines", secondary_res="eTG Paediatrics", rapid_review="Doses + red flags card", url="https://www.rch.org.au/clinicalguide/"),
 dict(domain="Older persons / RACF", primary_res="RACGP Silver Book", secondary_res="Aged care standards; deprescribing guides", rapid_review="Deprescribing triggers card", url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/silver-book"),
 dict(domain="Palliative care", primary_res="eTG Palliative Care", secondary_res="Palliative Care Australia / CareSearch", rapid_review="Anticipatory drugs card", url="https://tg.org.au"),
 dict(domain="Aboriginal and Torres Strait Islander health", primary_res="RACGP ATSI health resources + NACCHO", secondary_res="health.gov.au Closing the Gap; local AMS", rapid_review="715 + CTG items card", url="https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/atsi-health"),
 dict(domain="Musculoskeletal / arthritis", primary_res="RACGP OA guideline + ARA (Rheumatology) resources", secondary_res="Osteoporosis Australia (healthy bones)", rapid_review="Gout/OA/OP drug table", url="https://www.racgp.org.au/clinical-resources/clinical-guidelines"),
 dict(domain="Osteoporosis", primary_res="Osteoporosis Australia / Royal Aust College Physicians FRACX fracture prevention", secondary_res="eTG Musculoskeletal", rapid_review="Fragility-fracture action card", url="https://healthybonesaustralia.org.au"),
 dict(domain="Skin cancer", primary_res="Cancer Council Australia clinical guidelines (melanoma, NMSC)", secondary_res="RACGP skin cancer resources", rapid_review="Biopsy rule card", url="https://www.cancer.org.au/clinical-guidelines"),
 dict(domain="Eye", primary_res="RANZCO / Optometry Australia resources", secondary_res="eTG", rapid_review="Red-eye + vision loss triage card", url="https://www.ranzco.edu"),
 dict(domain="Travel medicine", primary_res="CDC Yellow Book / WHO; QLD Health travel advice", secondary_res="Travelvax Australia", rapid_review="Region-vaccine table", url="https://wwwnc.cdc.gov/travel"),
 dict(domain="Legal / ethics", primary_res="AHPRA + AMA + RACGP ethics guidance", secondary_res="Austroads Fitness to Drive", rapid_review="Mandatory reporting list", url="https://www.medicalboard.gov.au"),
 dict(domain="Health systems / Medicare", primary_res="MBS online + Services Australia", secondary_res="RACGP business in practice", rapid_review="GP item card (715, 721-723, health assessments)", url="http://mbsonline.gov.au"),
 dict(domain="Refugee / migrant health", primary_res="ASID/RACGP refugee health resources", secondary_res="Foundation House", rapid_review="Arrival screen checklist", url="https://www.racgp.org.au/clinical-resources/clinical-guidelines"),
 dict(domain="QLD-specific pathways", primary_res="QLD Health Clinical Guidelines + HealthPathways (Metro South access via MSH)", secondary_res="Metro South Health intranet", rapid_review="Local referral contacts card", url="https://www.health.qld.gov.au/clinical-practice-guidelines"),
]
(D / "resources.json").write_text(json.dumps(resources, indent=1), encoding="utf-8")
print("Resources:", len(resources))

rapid = [
 dict(title="Emergency red flags",
  content="STEMI: 000 + aspirin. | Sepsis: confusion + RR>=22 + SBP<=100 = 000. | Anaphylaxis: IM adrenaline 500 mcg 1:1000 anterolateral thigh, repeat 5 min. | Meningococcal: fever + non-blanching rash = ED. | Ectopic: positive pregnancy test + abdominal pain/pv bleeding + shoulder tip = ED. | Cauda equina: saddle anaesthesia/urinary retention = ED. | Cord compression (cancer): new weakness = MRI today. | Visible haematuria >40y: urgent urology. | Infant <3/12 fever: ED. | Chemical eye: irrigate 30 min first. | Acute vision loss: same-day ED. | Hanging/attempted suicide: same-day psychiatry."),
 dict(title="Paediatric red flags",
  content="<3 months + fever 38 = ED. | Drowsy/ill-looking/inconsolable = ED. | Petechiae + fever = ED. | Grunting, severe recession, SpO2<92% = ED. | Bile-stained vomit = ED surgical. | Fever >5 days (think Kawasaki). | Non-blanching rash. | Dehydration: dry mucosae, no urine >8h, sunken fontanelle. | Meningeal signs. | Abdominal pain + flexed hips (intussusception)."),
 dict(title="Pregnancy red flags",
  content="BP >=140/90 = same-day review; >=160/110 + symptoms = ED. | Severe headache, visual changes, RUQ pain = pre-eclampsia until proven otherwise. | PV bleeding + pain in 1st trimester = ectopic until excluded (bhCG + US). | Reduced movements >26 weeks = obstetric review same day. | Rupture of membranes + fever = ED. | Heavy bleeding any stage = ED."),
 dict(title="Medication contraindications (top tested)",
  content="DOACs: eGFR thresholds per drug; mechanical valves = warfarin only. | Metformin: eGFR caution <30 stop. | NSAIDs: avoid eGFR<60, GI bleed risk, heart failure. | ACEi/ARB: pregnancy contraindicated. | Warfarin: pregnancy (except specific valve cases). | Isotretinoin: pregnancy ABSOLUTE. | Methotrexate: pregnancy, heavy alcohol. | Valproate: pregnancy ABSOLUTE (unless no alternative). | DOAC + strong CYP3A4 inhibitors. | Trimethoprim: eGFR<30 + hyperkalaemia + potassium-sparing combos. | Beta blockers: asthma (relative), severe bradycardia. | Amiodarone: thyroid disease, iodine allergy. | Propylthiouracil: pregnancy preferred over methimazole/carbimazole (teratogenicity data)."),
 dict(title="Screening intervals (Australia, current)",
  content="Cervical: 25-74, HPV every 5 years, self-collect available; exit 70-74. | Bowel: 45-74, iFOBT every 2 years. | Breast: 50-74, 2-yearly (40-49 eligible). | CVD risk: 45-74 (30+ ATSI), 5-yearly recall. | T2DM risk: every 3 years from 40 (18 high-risk). | 715 health check: annual ATSI. | 75+ health assessment: annual. | Osteoporosis DEXA: not population screened; test after fragility fracture or risk factors."),
 dict(title="Immunisation quick sheet (post-2026 changes)",
  content="Adults >=70: 21vPCV (12 months after any previous pneumococcal). | ATSI >=50: 21vPCV. | Risk groups incl. COPD + chronic liver disease: NIP-funded 21vPCV. | Influenza: annual >=6 months; <9y first year = 2 doses 4 weeks apart. | RSV: program per 2025-26 arrangements (pregnancy and infant programs). | Pertussis: 20-32 weeks each pregnancy. | MenB: paracetamol prophylaxis with dosing in infants. | dTpa booster: every 10 years for HCWs/65+ per ATAGI 2026 advice (not NIP)."),
 dict(title="Diabetes targets",
  content="HbA1c: generally <=7% (individualise: <65y fit 6.5-7%; frail/elderly 7.5-8.5%). | BP: <130/80 if CKD/young; <140/90 older. | Lipids: statin per absolute risk; diabetes >=50 = statin. | Retinal, foot (monofilament), ACR: annually. | eGFR/UEC at least annually. | Weight: 5-10% loss changes trajectory."),
 dict(title="CVS risk numbers",
  content="Risk bands: low <10%, moderate 10-15%, high >15% (5-year). | Treat high risk with statin + BP. | Established CVD, diabetes >=50y, CKD with proteinuria, FH: treat as high risk regardless of score. | Start assessment at 45 (30 ATSI). | BP thresholds: treatment individualised to absolute risk; generally treat confirmed >=140/90."),
 dict(title="CKD staging",
  content="G1 eGFR >=90, G2 60-89, G3a 45-59, G3b 30-44, G4 15-29, G5 <15. | A1 ACR <3, A2 3-30, A3 >30 mg/mmol. | Refer: eGFR <30, ACR >60, persistent haematuria + proteinuria, rapid decline, refractory HTN. | Actions: RAAS blockade if A2+, SGLT2i if A2+/G3+, avoid NSAIDs + dehydration + contrast prep."),
 dict(title="Anaemia approach",
  content="Microcytic: iron deficiency (find the cause! men/postmenopausal = GI malignancy workup; premenopausal = menstrual most likely but exclude coeliac). Ferritin <30 = deficient. | Macrocytic: B12/folate, alcohol, hypothyroid, MDS. | Normocytic: CKD, inflammation, marrow. | Reticulocytes tell production story. | Always: repeat to confirm + review blood film."),
 dict(title="Thyroid interpretation",
  content="TSH high + fT4 low = overt hypothyroidism: treat. | TSH high + fT4 normal = subclinical: repeat 6-8w; treat if TSH >10, pregnancy/infertility, symptoms, or rising. | TSH low + fT4 high = overt thyrotoxicosis: treat/Refer. | TSH low + fT4 normal = subclinical hyper: repeat; assess cause. | Pregnancy TSH targets tighter (trimester-specific)."),
 dict(title="Mental health risk assessment",
  content="Ask: thoughts, plan, means, access, intent, timeframe. | Past attempts = strongest predictor. | Protective: children, supports, engagement, future plans. | Act: safety plan, means restriction, follow-up in days, crisis numbers. | Never: no-suicide contracts. | QLD Mental Health Line: 1300 642 255. | Qld Mental Health Act 2016: involuntary criteria = mental illness + risk to self/others + less-restrictive options exhausted."),
 dict(title="Mandatory reporting (QLD)",
  content="Children: reasonable suspicion of significant harm -> report to QLD Child Safety (mandatory for doctors). | Sexual activity <16: consider reporting; know consent laws. | Blood donors: mandatory. | Notifiable infectious diseases: QLD public health. | AHPRA: mandatory notification if doctor practising while intoxicated, substantially impaired, sex with patient, or placing public at risk (treating practitioner exemption applies to impairment)."),
 dict(title="Driving standards highlights",
  content="Dementia: assess function + on-road; report to transport authority. | Epilepsy: seizure-free per condition-specific periods (private typically 12 months). | Diabetes on insulin/SU: hypo awareness + 2-5 yearly reviews. | Syncope: investigate + per cause. | Sleep apnoea: severity + compliance + driving type. | Private vs commercial standards always differ. | Both patient and doctor have notification duties (QLD: police/transport)."),
 dict(title="Abnormal LFT approach",
  content="Repeat to confirm + pattern: hepatocellular (ALT) vs cholestatic (ALP+GGT). | Screen: viral B/C, ferritin/TSAT, UEC, ultrasound; autoimmune if not settling. | MASLD workup: metabolic context + FIB-4. | Isolated high ALP: GGT confirms liver vs bone source. | ALT >2x ULN persistent = full workup. | Alcohol: CAGE + granulocyte ratio. | Drug culprits: amoxiclav, statins, methotrexate, flucloxacillin, herbal."),
 dict(title="Antibiotic quick picks (eTG-aligned)",
  content="UTI (uncomplicated, female): nitrofurantoin 100 mg bd 5 days (first-line). | Cellulitis: flucloxacillin 500 mg qid 5-7d. | Community pneumonia: amoxycillin 1g tds; atypical cover doxycycline (or macro) if suspected. | Sinusitis: none unless >10-14d worsening pattern. | Strep pharyngitis: penicillin V 500 bd 10d. | Impetigo: topical if localised; oral if extensive. | Otitis media: watchful waiting 48-72h in most. | Bites: amoxycillin-clavulanate. | PID: ceftriaxone + doxycycline + metronidazole per guideline. | Qld far north strep: clindamycin resistance - use penicillin. | Sepsis: transfer; do not start oral abx.")
]
(D / "rapid_sheets.json").write_text(json.dumps(rapid, indent=1), encoding="utf-8")
print("Rapid sheets:", len(rapid))

# 18-week schedule to AKT/KFP 2027.1 (Jan 15/16), phases per user's spec
sched = []
week_plan = [
 (1,"1 - Foundation","Cardiovascular + preventive medicine"),
 (2,"1 - Foundation","Respiratory (asthma, COPD) + infectious disease basics"),
 (3,"1 - Foundation","Endocrine + renal (diabetes, thyroid, CKD)"),
 (4,"1 - Foundation","Mental health + suicide risk + addiction"),
 (5,"1 - Foundation","Women's health + contraception + antenatal"),
 (6,"1 - Foundation","Paediatrics + child development"),
 (7,"1 - Foundation","Older persons + polypharmacy + palliative"),
 (8,"1 - Foundation","Musculoskeletal + dermatology + skin cancer"),
 (9,"2 - Consolidation","Presentations I: chest pain, dyspnoea, cough, haemoptysis"),
 (10,"2 - Consolidation","Presentations II: fatigue, weight loss, headache, dizziness"),
 (11,"2 - Consolidation","Presentations III: abdominal pain, LFTs, GI, haematuria"),
 (12,"2 - Consolidation","Presentations IV: rash, joint pain, back pain, falls"),
 (13,"2 - Consolidation","Aboriginal + Torres Strait Islander health; refugee/migrant health"),
 (14,"2 - Consolidation","Ethics, law, mandatory reporting, driving, Medicare"),
 (15,"3 - Exam prep","Timed AKT blocks + KFP technique drills + error review"),
 (16,"3 - Exam prep","Full mock: 150 AKT (4h) + 70 KFP (4h) + review"),
 (17,"4 - Final revision","Weak areas + guideline rapid sheets + numbers"),
 (18,"4 - Final revision","Final week: rapid revision sheets, sleep, exam logistics"),
]
for wk, phase, focus in week_plan:
    sched.append(dict(week=wk, phase=phase, focus=focus,
        objectives="Cover the week's topics via the topic list; complete all AKT/KFP items; log errors to mistake log.",
        activities="Weekdays: 20 min topic review + 20 min questions + 10 min mistake review. Weekend: 2-4 h deep session incl. one CCE practice case per week from week 5."))
(D / "schedule.json").write_text(json.dumps(sched, indent=1), encoding="utf-8")
print("Schedule:", len(sched), "weeks")

print("ALL SEED FILES BUILT")
