#!/usr/bin/env python
"""Curriculum v3: every unit in the official RACGP 7-section format.
Sections: 1 Rationale, 2 Competencies and learning outcomes, 3 Curricula in context (link),
4 Case consultation example, 5 Learning strategies, 6 Guiding topics (topics table),
7 Learning resources (guidelines + materials with sources)."""
import json, pathlib

D = pathlib.Path(__file__).parent / "data"
BASE = "https://www.racgp.org.au/education/education-providers/curriculum/curriculum-and-syllabus/units/"

def U(type_, number, name, slug, rationale, comps, case, strat, guidelines, materials, *_ignored):
    return dict(type=type_, number=number, name=name, racgp_url=BASE+slug, rationale=rationale,
                competencies=comps, case_example=case, learning_strategies=strat,
                guidelines=guidelines, materials=materials)

def G(t, url, tier=1): return dict(title=t, url=url, tier=tier)
def M(l, url, kind="reference"): return dict(label=l, url=url, kind=kind)

ETG = "https://tg.org.au"
RB = "https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/red-book"
AIH = "https://immunisationhandbook.health.gov.au/"

units = [
# ============ CORE UNITS (7) ============
U("core",1,"Communication and the patient–doctor relationship","1-communication-and-the-patient-doctor-relationship",
 "The consultation is the core intervention of general practice. Effective, empathic communication improves accuracy of diagnosis, patient adherence, satisfaction and outcomes, and reduces medico-legal risk.",
 ["Open the consultation, elicit the patient's ideas, concerns and expectations, and close with a clear, mutually agreed plan",
  "Adapt communication to health literacy, culture, language (interpreters) and disability",
  "Break bad news with a structured approach, manage strong emotions and consult safely with children, adolescents and older people"],
 "A 45-year-old presents with 'tiredness'. As the consultation unfolds, three separate concerns emerge: her own tiredness, her father's recent cancer diagnosis, and a request for a medical certificate. (CCE areas: data gathering - elicit all three agendas; clinical management - prioritise; communication - agenda-setting, ICE, summarising.)",
 ["Record (with consent) one of your own consultations each week and review it against a consultation model",
  "Practise breaking bad news aloud with a study partner using SPIKES",
  "Ask your supervisor to observe a consultation and give structured feedback"],
 [G("RACGP unit page (official)",BASE+"1-communication-and-the-patient-doctor-relationship"), G("RACGP Curriculum and syllabus guide","https://www.racgp.org.au/education/education-providers/curriculum/curriculum-and-syllabus/a-guide-to-using-the-curriculum-and-syllabus")],
 [M("RACGP gplearning communication modules","https://www.racgp.org.au/education/professional-development/online-learning/gplearning","course")]),
U("core",2,"Applied professional knowledge and skills","2-applied-professional-knowledge-and-skills",
 "The GP applies clinical knowledge through reasoning: history, examination, differential diagnosis, targeted investigation and safe management - the engine room of the KFP and daily practice.",
 ["Take a focused history and perform a relevant, respectful examination",
  "Generate a pragmatic differential diagnosis and choose investigations that change management (avoiding over-investigation)",
  "Interpret results in context, prescribe safely, perform common GP procedures, and manage clinical uncertainty"],
 "A 52-year-old has 3 weeks of fatigue. First-line tests show ferritin 12 with normal Hb. (CCE areas: data gathering - menstrual, dietary, GI symptoms; clinical management - iron deficiency needs a cause: coeliac screen, GI malignancy considerations by age/sex; communication - explaining why 'a bit low in iron' still needs investigation.)",
 ["Do 20 AKT questions daily and log error patterns in your mistake log",
  "Case-based discussion with your supervisor on 2 undifferentiated presentations per week",
  "Practise a structured approach to abnormal results (anaemia, LFTs, electrolytes)"],
 [G("eTG complete (Therapeutic Guidelines)",ETG), G("Australian Medicines Handbook","https://amhonline.amh.net.au")],
 [M("eTG app - daily point-of-care use",ETG,"tool"),M("RACGP unit page (official)",BASE+"2-applied-professional-knowledge-and-skills","link")]),
U("core",3,"Population health and the context of general practice","3-population-health-and-the-context-of-general-practice",
 "GPs deliver preventive care at scale: screening programs, immunisation, notifiable disease management and health equity. Population thinking turns individual consultations into community outcomes.",
 ["Apply epidemiology when offering screening (benefits, harms, intervals)",
  "Run preventive activities systematically (Red Book) and use practice recall systems",
  "Recognise and act on health inequity; manage notifiable conditions and public health risks"],
 "A 54-year-old attends for a script refill. Her screening is overdue: bowel, cervical. (CCE areas: data gathering - what she already knows; clinical management - opportunistic offer of iFOBT and CST, immunisation status; communication - prevention in a time-poor consult without lecturing.)",
 ["Audit 10 consecutive patient files for due preventive activities",
  "Memorise current program intervals (cervical 25-74/5-yearly HPV, bowel 45-74/2-yearly iFOBT, BreastScreen 50-74)",
  "Write a one-page practice plan for improving under-screened groups"],
 [G("RACGP Red Book 10th ed (2024)",RB), G("Australian Immunisation Handbook",AIH), G("Dept of Health - screening programs","https://www.health.gov.au/topics/health-prevention")],
 [M("Red Book online (searchable)",RB,"reference"),M("AIH digital",AIH,"reference")]),
U("core",4,"Professional and ethical role","4-professional-and-ethical-role",
 "Professionalism underpins patient trust: ethical reasoning, confidentiality, consent, duty of candour, and care of the doctor's own health and that of colleagues.",
 ["Apply ethical frameworks to consent, capacity and confidentiality dilemmas",
  "Meet mandatory reporting obligations and know the limits of confidentiality",
  "Maintain own health, recognise colleague impairment, and practise within competence"],
 "A colleague at your practice seems increasingly withdrawn and smells of alcohol at morning tea. (CCE areas: clinical management - patient safety duties, doctors' health pathways, mandatory notification thresholds; communication - the supportive colleague conversation; professionalism - documentation.)",
 ["Discuss 2 ethics vignettes per fortnight with a study group",
  "Learn your state's mandatory reporting and child protection numbers by heart",
  "Complete an AHPRA code-of-conduct self-review"],
 [G("Medical Board - Good medical practice code","https://www.medicalboard.gov.au/Codes-Guidelines-Policies/Code-of-conduct.aspx"), G("AHPRA mandatory notifications","https://www.ahpra.gov.au/notifications/mandatory-notifications.aspx")],
 [M("Doctors' Health Service Queensland","https://www.drs4drs.com.au","org"),M("RACGP unit page (official)",BASE+"4-professional-and-ethical-role","link")]),
U("core",5,"Organisational and legal dimensions","5-organisational-and-legal-dimensions",
 "Safe general practice runs on systems: records, results handling, prescribing safety, privacy, employment law and quality improvement. Organisational failures - not knowledge failures - cause much preventable harm.",
 ["Keep contemporaneous, adequate records; apply privacy principles and appropriate confidentiality",
  "Run safe results and recall systems; manage referrals and prescribing within MBS/PBS rules",
  "Know key legal duties: certification, driving fitness, mandatory reporting, and respond to incidents openly"],
 "A patient telephones: 'Did anyone get my biopsy result? I had it 6 weeks ago.' No result was ever actioned. (CCE areas: clinical management - open disclosure, urgent retrieval and clinical assessment; professionalism - incident reporting and system fix; communication - the honest, apologetic conversation.)",
 ["Do a mock audit of your practice's results-tracking system",
  "Learn the common MBS item numbers used weekly in your practice",
  "Practise writing one defensible referral letter and one certificate per week"],
 [G("Austroads - Assessing Fitness to Drive","https://austroads.com.au/drivers-and-vehicles/driver-health/assessing-fitness-to-drive"), G("MBS Online","http://mbsonline.gov.au"), G("OAIC - health privacy","https://www.oaic.gov.au/privacy/privacy-guidance-for-organisations-and-government-agencies/health-services/")],
 [M("RACGP practice standards and tools","https://www.racgp.org.au/running-a-practice/practice-standards","reference")]),
U("core",6,"Aboriginal and Torres Strait Islander health","6-aboriginal-and-torres-strait-islander-health",
 "Aboriginal and Torres Strait Islander peoples experience a burden of disease 2-3 times the non-Indigenous rate, with earlier onset chronic disease. Culturally safe, high-trust general practice closes gaps: annual health checks, earlier risk assessment, CTG scripts and working with community-controlled services.",
 ["Deliver culturally safe care: ask about identification respectfully, build trust, understand institutional barriers and intergenerational trauma",
  "Deliver the annual 715 health check and Close the Gap PBS entitlements; start CVD risk assessment from 35 and diabetes screening earlier",
  "Work with ATSI community-controlled health services and local referral pathways; support patient self-determination"],
 "A 52-year-old Aboriginal man presents with tiredness; HbA1c returns 7.2%. His father died of kidney disease. He is wary of hospitals. (CCE areas: data gathering - family history, previous screening; clinical management - confirm diagnosis, cycle of care, CTG entitlements, vaccination; communication - plain language, trust, service choice.)",
 ["Complete RACGP ATSI health activity on gplearning",
  "Learn the 715, CTG script and follow-up item numbers cold",
  "Visit or arrange a visit to your local ATSI community-controlled health service"],
 [G("National guide to preventive healthcare for ATSI people (3rd ed)","https://racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/national-guide"), G("RACGP ATSI health unit page",BASE+"6-aboriginal-and-torres-strait-islander-health"), G("Australian Institute of Health and Welfare - ATSI health reports","https://www.aihw.gov.au/reports/indigenous-australians")],
 [M("NACCHO","https://www.naccho.org.au","org"),M("AIATSIS map of Indigenous Australia","https://aiatsis.gov.au/explore/map-indigenous-australia","map")]),
U("core",7,"Rural health","rural-health",
 "Rural GPs work with extended scope, greater distance from specialist services and different workforce realities: telehealth, retrieval, and managing emergencies that urban colleagues refer out.",
 ["Stabilise and coordinate emergencies with longer transfer times; know local retrieval pathways",
  "Use telehealth effectively and coordinate care across distances",
  "Manage the professional isolation and on-call realities of rural practice; maintain skills and self-care"],
 "You are the only doctor in a small town. A 60-year-old collapses with chest pain; the nearest PCI hospital is 90 minutes by road. (CCE areas: data gathering - ECG, history in parallel with treatment; clinical management - pre-hospital STEMI pathway, aspirin, GTN, oxygen if hypoxic, 000/retrieval; communication - calm coordination, family updates.)",
 ["Rehearse your practice's emergency drug trolley and anaphylaxis/STEMI/stroke workflows",
  "Complete a rural emergency skills course (or refresh) if applicable to your scope",
  "Write out your local after-hours and retrieval phone tree"],
 [G("RACGP rural health unit page",BASE+"rural-health"), G("Services Australia - telehealth items","https://www.servicesaustralia.gov.au/medicare-benefits-health-professionals")],
 [M("ACRRM/rural emergency resources","https://www.acrrm.org.au","org")]),

# ============ CONTEXTUAL UNITS (35) ============
U("contextual",1,"Abuse and violence","abuse-and-violence",
 "Family and domestic violence affects about 1 in 4 women presenting to general practice; GPs are often the first and sometimes the only professional a victim discloses to. Recognition, safety assessment and patient-paced response save lives; child safety obligations run alongside.",
 ["Ask directly and privately, believe, validate, and assess immediate safety including strangulation risk",
  "Safety-plan, document meticulously (verbatim, body maps), and connect to FDV services; never force leaving",
  "Meet mandatory child protection obligations when children are exposed"],
 "A 38-year-old woman discloses ongoing violence from her partner; she is not ready to leave. Two children at home. (CCE areas: data gathering - privacy, pattern, strangulation, children; clinical management - safety assessment, safety plan, 1800RESPECT, child protection duty; communication - patient-paced, non-directive.)",
 ["Read the RACGP White Book end-to-end once; re-read the safety assessment chapter",
 "Practise the first-response script aloud: validation without pressure",
 "Memorise local FDV services, the Elder Abuse helpline and Child Safety number"],
 [G("RACGP White Book - Abuse and violence","https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/white-book"), G("1800RESPECT clinical resources","https://www.1800respect.org.au")],
 [M("QLD Domestic Violence Protection Act resources / DV Connect","https://www.dvconnect.org","org")]),
U("contextual",2,"Addiction medicine","addiction-medicine",
 "Alcohol, tobacco and other drug problems are among the highest-burden conditions GPs manage. Brief interventions work; pharmacotherapies (smoking, opioid, alcohol) are GP-deliverable; withdrawal states are medical emergencies in the dependent.",
 ["Screen with AUDIT-C and deliver brief intervention for alcohol and smoking (Ask-Advise-Help)",
  "Manage alcohol withdrawal risk (CIWA-Ar, thiamine before glucose) and opioid dependence (buprenorphine/methadone pathways)",
  "Prescribe pharmacotherapy for smoking cessation (varenicline first-line, combination NRT) and reduce harms for all substance use"],
 "A 50-year-old drinks 80 g/day and is booked for surgery next week. (CCE areas: data gathering - quantity, withdrawal history, past seizures/delirium; clinical management - withdrawal risk stratification, thiamine, hospital liaison; communication - motivation without confrontation.)",
 ["Learn the alcohol withdrawal ladder and thiamine rules cold",
 "Do the RACGP smoking cessation module; memorise varenicline dosing and cautions",
 "Write out the opioid substitution pathway in your state"],
 [G("eTG Psychotropic (alcohol/drug sections)",ETG), G("RACGP smoking cessation guideline","https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/smoking-cessation"), G("Quitline resources","https://www.quit.org.au")],
 [M("Turning Point education","https://www.turningpoint.org.au","org")]),
U("contextual",3,"Cardiovascular health","cardiovascular-health",
 "CVD is Australia's leading cause of death: 26% of all deaths. GPs control the levers - absolute risk assessment, BP, lipids, anticoagulation in AF, and post-event secondary prevention. ATSI adults carry double the mortality, with risk assessment from 35.",
 ["Assess and manage absolute CVD risk (Aus CVD Risk Calculator; treat risk, not single numbers)",
  "Diagnose and manage hypertension (confirm out-of-office), AF (CHA2DS2-VA anticoagulation), and heart failure (quadruple therapy)",
  "Recognise and refer ACS, aortic dissection and severe valve disease emergently; run post-ACS secondary prevention"],
 "A 62-year-old has 2 hours of central chest pain in your practice. ECG: ST elevation V2-V4. (CCE areas: data gathering - focused pain history, risk factors in parallel; clinical management - 000, aspirin 300, GTN if BP allows, PCI transfer; communication - calm urgency, family informed.)",
 ["Master the 2023 CVD risk guideline thresholds and the AF anticoagulation decision",
 "Write the HFrEF quadruple therapy from memory weekly until automatic",
 "Rehearse the practice STEMI/anaphylaxis drill"],
 [G("2023 Australian CVD Risk guideline + calculator","https://www.heartfoundation.org.au/for-professionals/clinical-resources/cardiovascular-disease-risk-assessment"), G("Australian AF guideline (2018)","https://www.heartfoundation.org.au/for-professionals/clinical-resources/atrial-fibrillation-resources"), G("Heart Foundation hypertension resources","https://www.heartfoundation.org.au/for-professionals/clinical-resources/hypertension"), G("ACS guideline 2025","https://www.heartfoundation.org.au/for-professionals/clinical-resources/acute-coronary-syndromes"), G("eTG Cardiovascular",ETG)],
 [M("Aus CVD Risk Calculator","https://www.cvdcheck.org.au","tool"),M("Heart Foundation professional hub","https://www.heartfoundation.org.au/for-professionals","org")]),
U("contextual",4,"Child and youth health","child-and-youth-health",
 "Children are a large share of GP presentations: infections, development, behaviour, and adolescent health. Weight and height are vital signs; fever management is risk-stratified; safeguarding duties run through everything.",
 ["Assess the febrile child by risk (traffic-light); manage common conditions per RCH guidelines (bronchiolitis, croup, otitis media)",
  "Track growth and development; recognise autism/ADHD and refer via correct pathways",
  "Consult adolescents headssfully: confidentiality and its limits; mandatory reporting for abuse"],
 "A 6-month-old has fever 38.8 for 24 hours, alert and drinking. (CCE areas: data gathering - traffic-light features; clinical management - green category, safety-netting, no antibiotics; communication - clear when-to-return advice.)",
 ["Learn the fever traffic-light table and the under-3-months rule cold",
 "Bookmark RCH CPGs; do the bronchiolitis, croup, and gastro guidelines end-to-end",
 "Do one HEADSS practice consultation with a teen in your clinic this month"],
 [G("RCH Clinical Practice Guidelines","https://www.rch.org.au/clinicalguide/"), G("Red Book - child screening sections",RB), G("Australian Immunisation Handbook",AIH)],
 [M("Raising Children Network","https://raisingchildren.net.au","org")]),
U("contextual",5,"Dermatological presentations","dermatological-presentations",
 "Skin problems are ~15% of GP presentations and Australia has the world's highest skin cancer rates. The GP is the front line for melanoma detection, eczema/psoriasis management and skin surgery decisions.",
 ["Describe lesions systematically; biopsy correctly (excision for suspected melanoma - never shave)",
  "Manage eczema (steroid ladder, emollients, bleach baths), psoriasis (topical combinations, referral criteria), acne (stepwise, isotretinoin rules)",
  "Perform skin checks and recognise high-risk patients; know referral criteria for lesions and wounds"],
 "A 40-year-old asks review of a 7 mm changing pigmented lesion on his back with varied colours. (CCE areas: data gathering - ABCD/E, change, risk factors; clinical management - excision biopsy 2 mm margin, dermoscopy where trained; communication - explaining why 'just removing it' must be done properly.)",
 ["Practise describing 10 lesions aloud using formal morphology language",
 "Memorise biopsy margins and which lesions never to shave",
 "Do a dermoscopy basics module if available locally"],
 [G("Cancer Council Australia - melanoma/NMSC guidelines","https://www.cancer.org.au/clinical-guidelines"), G("eTG Dermatology",ETG)],
 [M("SunSmart / Cancer Council resources","https://www.cancer.org.au","org")]),
U("contextual",6,"Disability care","disability-care",
 "People with disability face the greatest health inequities: undiagnosed pain, missed prevention, diagnostic overshadowing. The GP's job is ordinary excellent care, delivered accessibly, plus NDIS literacy.",
 ["Deliver annual health assessments for patients with intellectual/physical disability with reasonable adjustments",
  "Communicate with AAC users, carers and support workers; assess capacity decision-by-decision",
  "Navigate the NDIS: reports, allied health coordination, and advocacy for health needs"],
 "A 25-year-old woman with cerebral palsy and intellectual disability presents with new agitation; her support worker says 'she's always like this'. (CCE areas: data gathering - pain/constipation/reflux/UTI as equal possibilities, obtaining history from multiple sources; clinical management - treat the cause, not the behaviour; communication - direct address, capacity respect.)",
 ["Read the RACGP position on care of patients with disability",
 "Learn the health assessment item numbers for patients with disability",
 "Audit 5 files of patients with disability for missed prevention"],
 [G("RACGP - health of people with disabilities","https://www.racgp.org.au/clinical-resources/clinical-guidelines"), G("NDIS resources for GPs","https://www.ndis.gov.au")],
 [M("Council for Intellectual Disability resources","https://cid.org.au","org")]),
U("contextual",7,"Disaster health","disaster-health",
 "GPs are embedded in every disaster response - fires, floods, pandemics: continuity of care for the vulnerable, public health measures, and practice business continuity.",
 ["Maintain care continuity for high-risk patients during disruption (medication supply, telehealth)",
  "Apply public health directions and outbreak principles; know your role and limits in activation",
  "Plan practice continuity: records access, remote work, staff safety"],
 "A flood has cut power to your practice for 3 days; several patients on insulin and warfarin are stranded without medication. (CCE areas: data gathering - identify the vulnerable cohort; clinical management - alternative supply, relocation of care; professionalism - proactive outreach.)",
 ["Write a one-page practice continuity plan for your top 3 local risks",
 "Complete an emergency/incident management module"],
 [G("Australian Disaster Resilience Hub","https://knowledge.aidr.org.au"), G("Dept of Health emergency response","https://www.health.gov.au")],
 [M("RACGP disaster management resources","https://www.racgp.org.au/running-a-practice","reference")]),
U("contextual",8,"Doctors' health","doctors-health",
 "Doctors have elevated rates of mental illness, substance use and suicide, and are notoriously poor patients. Confidential, doctor-to-doctor care pathways exist; the treating doctor generally does NOT face mandatory notification for treating impairment.",
 ["Encourage every doctor to have their own GP; provide non-judgemental care to colleagues",
  "Recognise burnout, depression, substance use in self and colleagues; intervene supportively early",
  "Know doctors' health services (drs4drs) and the boundaries of the treating-physician notification exemption"],
 "A 29-year-old intern confesses to 6+ drinks nightly to sleep, plus zopiclone from a sample pack, terrified of exposure. (CCE areas: data gathering - severity, risk, work impact; clinical management - safer sleep plan, alcohol taper, doctors' health service, own GP; professionalism - confidentiality within legal limits.)",
 ["Save the Doctors' Health Service number in your phone now",
 "Read the treating-practitioner exemption rules once carefully"],
 [G("Converge / Doctors' Health Service","https://www.drs4drs.com.au"), G("RACGP doctors' health resources","https://www.racgp.org.au/running-a-practice/your-health")],
 [M("drs4drs Queensland","https://www.drs4drs.com.au","org")]),
U("contextual",9,"Ear, nose, throat and oral health","ear-nose-throat-and-oral-health",
 "ENT complaints fill waiting rooms: otitis media (watchful waiting criteria), sore throat (Centor), sinusitis, hearing loss, epistaxis first aid, and oral lesions with cancer red flags.",
 ["Manage AOM with analgesia-first and defined antibiotic triggers; treat otitis externa topically",
  "Triage sore throat (Centor, penicillin), sinusitis (>10 days worsening), and epistaxis (pressure first-line)",
  "Assess hearing loss (Rinne/Weber patterns) and refer; recognise non-healing oral ulcers (3 weeks) urgently"],
 "A 2-year-old with bilateral AOM, 48 hours, distressed but systemically well. (CCE areas: data gathering - analgesia adequacy, red flags; clinical management - delayed prescribing/watchful waiting; communication - what to watch for, when to return.)",
 ["Memorise AOM immediate-antibiotic criteria and the 3-week oral ulcer rule",
 "Practise Rinne/Weber interpretation on 5 cases"],
 [G("eTG Respiratory (ENT sections)",ETG), G("RCH CPG - otitis media","https://www.rch.org.au/clinicalguide/")],
 [M("Hearing Australia","https://www.hearing.com.au","org")]),
U("contextual",10,"Education in general practice","education-in-general-practice",
 "Teaching is a core professional role: supervising students and registrars, giving feedback, and teaching patients. Good teaching improves the whole practice's care.",
 ["Give structured feedback (set-readiness, observe, debrief)",
  "Teach in the consultation efficiently (One-Minute Preceptor, SNAPPS)",
  "Support learners in difficulty and manage the failing student fairly"],
 "A final-year student presents a case badly; you have a full waiting room. (CCE areas: clinical management - model efficient teaching; professionalism - feedback culture; communication - educational alliance.)",
 ["Practise the One-Minute Preencer structure three times this week"],
 [G("RACGP education unit page",BASE+"education-in-general-practice")],
 [M("gplearning teaching modules","https://www.racgp.org.au/education/professional-development/online-learning/gplearning","course")]),
U("contextual",11,"Emergency medicine","emergency-medicine",
 "GP surgeries are unplanned-care sites: anaphylaxis, sepsis, ACS, stroke, trauma and collapse all walk through the door. Outcomes depend on recognition, first-line treatment and timely transfer.",
 ["Deliver IM adrenaline for anaphylaxis (0.5 mg adult, thigh, repeat 5 min) and salbutamol/steroids for severe asthma",
  "Recognise sepsis (qSOFA) and stroke (FAST); transfer 000 with pre-alert",
  "Run a practice emergency trolley: adrenaline, salbutamol, GTN, aspirin, glucometer, defibrillator"],
 "A patient collapses anaphylactic after an antibiotic injection in your treatment room. (CCE areas: clinical management - IM adrenaline, call 000, lie flat, IV access; communication - team leadership, family; professionalism - incident documentation.)",
 ["Run a team anaphylaxis drill this month; restock the trolley",
 "Write your top-10 surgery emergency protocols on one card"],
 [G("eTG Emergency",ETG), G("Australian Resuscitation Council guidelines","https://resus.org.au")],
 [M("ARC anaphylaxis flowchart (print for wall)","https://resus.org.au","tool")]),
U("contextual",12,"Endocrine and metabolic health","metabolic-and-endocrine-health",
 "Diabetes, obesity, thyroid and lipids dominate chronic GP care and exam blueprints equally. Modern management is comorbidity-driven (SGLT2i/GLP-1) and complication-screened (annual cycle).",
 ["Diagnose and manage T2DM: individualised HbA1c, comorbidity-based drug choice, annual complications screen",
  "Interpret thyroid function tests and manage overt/subclinical disease, including pregnancy",
  "Manage obesity as a chronic disease (5-10% goals, pharmacotherapy criteria) and lipids by absolute risk/FH rules"],
 "A 60-year-old with T2DM (HbA1c 8.5%), eGFR 62, on metformin and gliclazide, smokes. (CCE areas: data gathering - cycle-of-care gaps; clinical management - SGLT2i add-on, BP/lipid targets, smoking; communication - prioritising with the patient.)",
 ["Write the T2DM cycle of care and drug-choice ladder from memory weekly",
 "Master TFT interpretation including pregnancy and subclinical patterns"],
 [G("RACGP/Diabetes Australia - T2DM management","https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/type-2-diabetes"), G("ADS position statements","https://diabetessociety.com.au"), G("eTG Endocrine",ETG)],
 [M("Diabetes Australia","https://www.diabetesaustralia.com.au","org")]),
U("contextual",13,"Eye presentations","eye-presentations",
 "Sight-threatening emergencies present to GPs first: chemical injury (irrigate first), contact-lens keratitis, acute angle closure, retinal detachment, and GCA-related vision loss. Also: diabetic retinopathy screening and red-eye triage.",
 ["Irrigate chemical burns immediately (30 min) before anything else; assess pH",
  "Triage the red eye: pain, photophobia, vision loss, contact lenses = same-day ophthalmology",
  "Organise diabetic retinal screening and recognise glaucoma risk opportunistically"],
 "A 25-year-old contact-lens wearer has a painful red eye with photophobia and reduced vision. (CCE areas: data gathering - lens habits, overnight wear; clinical management - same-day ophthalmology, no patching, stop lenses; communication - sight-loss seriousness.)",
 ["Print the red-eye triage table and the chemical-injury protocol for your desk",
 "Learn the four sight-threatening headaches of the eye (angle closure, GCA, keratitis, detachment)"],
 [G("RANZCO / Optometry Australia resources","https://www.optometry.org.au"), G("eTG Eye",ETG)],
 [M("KeepSight (diabetic retinopathy recall)","https://www.keepsight.org.au","org")]),
U("contextual",14,"Gastrointestinal health","gastrointestinal-health",
 "GI symptoms are among the most common presentations: dyspepsia with alarm features, liver disease (MASLD, viral hepatitis), bowel screening positives, coeliac, IBS and iron deficiency.",
 ["Triage dysphagia/weight loss/anaemia urgently (scope, not PPI trials); manage GORD stepwise",
  "Work up abnormal LFTs systematically (pattern, viral serology, iron, ultrasound, FIB-4)",
  "Manage positive iFOBT (colonoscopy), coeliac (test before diet), and IBS positively (Rome IV, diet)"],
 "A 52-year-old asymptomatic man has ALT 95, BMI 33, negative serology. (CCE areas: data gathering - alcohol, meds, risk factors; clinical management - MASLD pathway: confirm, viral/iron/autoimmune screen, FIB-4; communication - fatty liver explanation and prognosis factors.)",
 ["Learn the LFT pattern approach and FIB-4 thresholds",
 "Memorise upper-GI alarm features and the iFOBT-positive action"],
 [G("GESA resources","https://www.gesa.org.au"), G("Cancer Council bowel screening resources","https://www.cancer.org.au"), G("eTG Gastrointestinal",ETG)],
 [M("Bowel Screening Program resources for GPs","https://www.health.gov.au/our-work/national-bowel-cancer-screening-program","reference")]),
U("contextual",15,"Haematological presentations","haematological-presentations",
 "Anaemia, abnormal clotting and blood count abnormalities are bread-and-butter GP interpretation; anticoagulation decisions and malignancy recognition (blasts, unexplained cytopenias) are high-stakes.",
 ["Classify anaemia by MCV and reticulocytes; find the cause (iron deficiency in adults = find the source)",
  "Anticoagulate appropriately (DOAC-first for AF/VTE; renal dosing, perioperative rules) and set VTE durations by provocation",
  "Recognise haematological emergencies: blasts on film, platelets <20, neutropenic fever - same-day haematology"],
 "A 63-year-old man has Hb 102, ferritin 8, microcytic. (CCE areas: data gathering - GI symptoms, diet, family history; clinical management - bidirectional endoscopy, iron replacement 3 months beyond normalisation; communication - why men need the scope.)",
 ["Drill the anaemia grid (micro/macro/normocytic) and iron rules",
 "Learn DOAC perioperative holding and the provoked vs unprovoked VTE durations"],
 [G("eTG Haematology",ETG), G("Blood resources - National Blood Authority","https://www.blood.gov.au")],
 [M("Anticoagulation reversal reference card","https://www.blood.gov.au","tool")]),
U("contextual",16,"Infectious diseases","infectious-diseases",
 "GPs prescribe most antibiotics in Australia: stewardship, first-line choices and notifiable disease duties sit with us. Add QLD-specific exposures (Q fever, melioidosis up north) and the returned traveller.",
 ["Choose antibiotics per eTG (UTI nitrofurantoin, cellulitis flucloxacillin, pneumonia amoxycillin) and de-escalate",
  "Diagnose and manage influenza, pertussis, TB risk, and febrile travellers (malaria same-day)",
  "Vaccinate per AIH including catch-ups; manage notifiable diseases and contact advice"],
 "A 46-year-old abattoir worker has 5 days of fever and headache in rural QLD. (CCE areas: data gathering - occupation, animals, travel; clinical management - Q fever: doxycycline, serology, notification; communication - occupational implications.)",
 ["Build a personal top-15 antibiotic table with doses and durations",
 "Learn the notifiable diseases list and your public health unit contact"],
 [G("Australian Immunisation Handbook",AIH), G("eTG Antibiotic",ETG), G("Australian STI guidelines (overlap)","http://sti.guidelines.org.au")],
 [M("NCIRS resources","https://www.ncirs.org.au","org"),M("QLD Health notifiable diseases","https://www.health.qld.gov.au","reference")]),
U("contextual",17,"Integrative medicine","integrative-medicine",
 "Many patients use complementary medicine: GPs must ask (half don't tell), check interactions, and communicate respectfully about evidence without destroying the relationship.",
 ["Ask routinely about all supplements and practitioners; document",
  "Check for interactions (warfarin/DOACs + fish oils, St John's wort with everything)",
  "Communicate evidence differences honestly; support safe choices, caution on harm"],
 "A patient on warfarin starts high-dose fish oil and ginkgo bought online, and her INR becomes erratic. (CCE areas: data gathering - full supplement list; clinical management - interaction management, INR safety net; communication - non-judgemental negotiation.)",
 ["Memorise the top-10 herbal-drug interactions"],
 [G("NPS MedicineWise","https://www.nps.org.au")],
 [M("NPS complementary medicine interactions checker","https://www.nps.org.au","tool")]),
U("contextual",18,"Justice system health","justice-system-health",
 "Prisoners and forensic patients have worse health than the general population; GPs working in or adjacent to the justice system manage high mental health, substance and chronic disease burdens with confidentiality subtleties.",
 ["Deliver equivalent care to people in custody; recognise the health consequences of incarceration",
  "Manage confidentiality within justice-system constraints (security present at consults)",
  "Coordinate with justice health services on release: continuity scripts, opioid programs"],
 "A man recently released from prison needs ongoing methadone, hepatitis C treatment and housing support. (CCE areas: data gathering - custody history, meds, risks; clinical management - DAA treatment, OST continuity, referrals; communication - trust and reintegration.)",
 ["Read one overview of prison health in Australia",
  "Learn the Medicare rules for custodial settings"],
 [G("Justice Health Queensland resources","https://www.health.qld.gov.au")],
 [M("Justice Health QLD clinical resources","https://www.health.qld.gov.au","org")],
 []),
U("contextual",19,"Kidney and urinary health","kidney-and-urinary-health",
 "CKD is silent, common and manageable in primary care: eGFR + ACR staging, RAAS blockade, SGLT2i and nephrotoxin avoidance change trajectories. Haematuria and LUTS triage are daily GP work.",
 ["Stage CKD (eGFR + ACR) and manage: BP, RAAS blockade with albuminuria, SGLT2i, sick-day rules",
  "Triage haematuria: visible = urological malignancy pathway; glomerular pattern = nephrology",
  "Manage UTI (nitrofurantoin first), stones, and LUTS stepwise; refer per criteria"],
 "A 68-year-old man, eGFR 38 and stable, has a gout flare asking for naproxen. (CCE areas: data gathering - meds, CKD stage; clinical management - NSAID avoidance, topical first, colchicine dose-adjusted; communication - analgesia explanation in CKD.)",
 ["Memorise CKD stages + referral criteria and the sick-day drug list",
 "Learn haematuria triage cold (visible vs glomerular)"],
 [G("Kidney Health Australia - CKD in primary care","https://kidney.org.au/health-professionals/chronic-kidney-disease-management-in-primary-care"), G("eTG Kidney/Urology",ETG)],
 [M("CKD management in primary care handbook","https://kidney.org.au","reference")]),
U("contextual",20,"Men's health","mens-health",
 "Men die younger and attend less: GP opportunities concentrate in chronic disease, mental health and suicide prevention, urological symptoms and ED as a cardiovascular flag.",
 ["Use ED as a CVD screening prompt (assess risk before sildenafil)",
  "Counsel on PSA with informed decision-making (benefits/harms; no population program)",
  "Screen opportunistically: BP, lipids, glucose, mental health in every male consult you can"],
 "A 56-year-old smoker with ED requests 'just a script for Viagra'. (CCE areas: data gathering - CVD risk factors, morning erections, mood; clinical management - risk assessment first, PDE5i with nitrate check; communication - reframing ED as a heart check.)",
 ["Learn the PSA conversation (screening vs informed choice) thoroughly",
 "Rehearse asking men about mood and suicide risk directly"],
 [G("Healthy Male (Andrology Australia)","https://www.healthymale.org.au"), G("Red Book men's sections",RB)],
 [M("Healthy Male GP resources","https://www.healthymale.org.au","org")]),
U("contextual",21,"Mental health","mental-health",
 "Mental illness is the third-largest burden of disease in Australia; GPs deliver most mental health care. Depression, anxiety, bipolar, psychosis, perinatal disorders and suicide risk are core GP competencies.",
 ["Screen (PHQ-9, GAD-7, EPDS, K10), assess suicide risk directly (plan/means/intent), and safety-plan (never contracts)",
  "Deliver stepped care: psychological therapy +/- SSRI with structured review (2 weeks tolerability, 4-6 response)",
  "Recognise bipolar/psychosis early and refer; manage perinatal and youth mental health within pathways"],
 "A 35-year-old woman with PHQ-9 = 18 has passive death wishes but no plan; two children at home. (CCE areas: data gathering - direct risk questions, protective factors, substances; clinical management - safety plan, same-week review, SSRI, referral; communication - hope, control, follow-through.)",
 ["Learn a suicide risk framework you can say out loud in 60 seconds",
 "Memorise the MH referral options in your area (mental health plan, crisis lines)"],
 [G("RACGP depression guidelines","https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/depression"), G("LIFE Framework (suicide prevention)","https://lifeinmindaustralia.com.au"), G("Beyond Blue primary care guides","https://www.beyondblue.org.au")],
 [M("QLD Mental Health Line 1300 642 255","tel:1300642255","tel"),M("Head to Health","https://headtohealth.gov.au","org")]),
U("contextual",22,"Migrant, refugee and asylum seeker health","migrant-refugee-and-asylum-seeker-health",
 "New arrivals carry specific health needs: refugee screening bundles, interpreter-mediated care, torture/trauma awareness, and visa-status effects on Medicare access.",
 ["Use professional interpreters always (TIS), speak to the patient, and confirm dialect",
  "Deliver arrival screening: hepatitis B, HIV, syphilis, TB, parasites; vaccinate and catch up",
  "Practise trauma-informed care: never force disclosure; navigate Medicare/visa issues kindly"],
 "A 28-year-old pregnant refugee from Africa, no English, first antenatal visit. (CCE areas: data gathering - interpreter, obstetric, exposure country; clinical management - booking labs + hep B/HIV/syphilis, TB screen, parasite screen; communication - teach-back, safety.)",
 ["Save the TIS Doctors line number; practise booking one",
 "Learn the refugee screening bundle by heart"],
 [G("ASID refugee health guidelines","https://www.asid.net.au"), G("Foundation House (torture/trauma)","https://www.foundationhouse.org.au")],
 [M("TIS National","https://www.tisnational.gov.au","tool")]),
U("contextual",23,"Military and veteran health","military-and-veteran-health",
 "Veterans carry distinct risks: PTSD, moral injury, hearing loss, musculoskeletal injury and higher suicide rates. DVA arrangements and veteran-aware care improve engagement.",
 ["Recognise service-related conditions (PTSD presentations, hearing, chronic pain) and ask about service history",
  "Navigate DVA funding: gold/white card entitlements and GP items",
  "Coordinate veteran mental health care with Open Arms and specialist services"],
 "A 45-year-old ex-serviceman has insomnia, irritability and heavy drinking since deployment. (CCE areas: data gathering - service history, PTSD screen, alcohol; clinical management - veteran-specific pathways, DVA, Open Arms; communication - trust, no assumptions.)",
 ["Learn the DVA card types and what they cover"],
 [G("DVA health provider resources","https://www.dva.gov.au/providers"), G("Open Arms","https://www.openarms.gov.au")],
 [M("Open Arms - Veterans & Families Counselling","https://www.openarms.gov.au","org")]),
U("contextual",24,"Musculoskeletal presentations","musculoskeletal-presentations",
 "MSK complaints are the most common reason for GP visits: backs, knees, shoulders, arthritis. Red flags first, imaging restraint second, function-focused management third.",
 ["Screen back pain red flags (cauda equina, cancer, infection, fracture) and manage most acute back pain without imaging",
  "Manage OA (exercise/weight loss first), gout (acute + ULT rules: start low, titrate to urate <0.30, prophylaxis), and RA (early referral)",
  "Assess injuries by structure (Ottawa rules); know when to image, inject, refer"],
 "A 34-year-old man has acute low back pain after lifting; no red flags. (CCE areas: data gathering - red flag screen; clinical management - stay active, heat, analgesia, no MRI; communication - reassurance and expected course.)",
 ["Memorise the back-pain red flag list and Ottawa ankle rules",
 "Learn allopurinol start-titrate-prophylaxis rules and the PMR/GCA pair"],
 [G("RACGP OA guideline","https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/osteoarthritis"), G("Healthy Bones Australia","https://healthybonesaustralia.org.au"), G("eTG Musculoskeletal",ETG)],
 [M("Arthritis Australia resources","https://arthritisaustralia.com.au","org")]),
U("contextual",25,"Neurological presentations","neurological-presentations",
 "Headache, dizziness, stroke, seizures and dementia are high-yield GP neurology: pattern recognition separates benign from urgent, and time matters in stroke care.",
 ["Triage headache red flags (thunderclap, fever, neurology, >50y new, GCA) and manage migraine with correct prophylaxis triggers",
  "Manage dizziness by pattern (BPPV: Dix-Hallpike/Epley) and recognise posterior circulation strokes",
  "Respond to TIA/seizure correctly (same-day TIA assessment; driving rules) and structure dementia workup (reversible causes)"],
 "A 70-year-old has 20 minutes of arm weakness yesterday; resolved today, feels well. (CCE areas: data gathering - deficit detail, risk factors; clinical management - same-day TIA pathway, ABCD2 not for triage in Australia, aspirin per pathway; communication - urgency despite feeling well.)",
 ["Write the headache red-flag list and the TIA same-day rule on a card",
 "Practise Dix-Hallpike/Epley on a colleague"],
 [G("Stroke Foundation - Clinical Guidelines","https://www.strokefoundation.org.au"), G("Austroads - neurological conditions and driving","https://austroads.com.au/drivers-and-vehicles/driver-health/assessing-fitness-to-drive")],
 [M("Stroke Foundation resources for GPs","https://www.strokefoundation.org.au","org")]),
U("contextual",26,"Occupational and environmental medicine","occupational-and-environmental-medicine",
 "Work drives health and health drives work capacity: certificates, return-to-work plans, occupational disease recognition (dermatitis, Q fever, noise) and environmental exposures.",
 ["Certify accurately (what you can verify); write return-to-work plans with specific duties",
  "Recognise occupational disease patterns (wet-work dermatitis, zoonoses, solvents) and link exposure to diagnosis",
  "Understand workers' compensation systems and the GP's reporting role"],
 "A 34-year-old hairdresser has hand dermatitis worse on workdays. (CCE areas: data gathering - exposure inventory, gloves, wet work; clinical management - allergen avoidance, topical ladder, notification for compensation; communication - work modification negotiation.)",
 ["Learn certificate-writing rules and your state's workers comp process"],
 [G("Safe Work Australia","https://www.safeworkaustralia.gov.au")],
 [M("Return to work coordinator resources","https://www.safeworkaustralia.gov.au","reference")]),
U("contextual",27,"Older persons' health","older-persons-health",
 "Frailty, multimorbidity and polypharmacy define care of older people: annual health assessments, deprescribing, falls, cognition and elder abuse. The aim is function and dignity, not number-chasing.",
 ["Deliver comprehensive geriatric assessment (75+ health assessment): function, falls, cognition, mood, meds, social",
  "Deprescribe systematically (fall-risk drugs, anticholinergics, PPIs without indication); individualise BP/HbA1c targets",
  "Recognise delirium (acute = cause hunt), elder abuse, and drive advance care planning early"],
 "An 85-year-old has 3 falls in 6 months on temazepam and doxazosin with postural drop. (CCE areas: data gathering - meds, home hazards, vision, strength; clinical management - deprescribe first, exercise, vitamin D if deficient; communication - goals-of-care conversation.)",
 ["Write the frailty-aware target list (when to relax BP/HbA1c)",
 "Learn the 4 AT delirium screen and the multifactorial falls pathway"],
 [G("RACGP Silver Book","https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/silver-book"), G("Austroads - older drivers","https://austroads.com.au/drivers-and-vehicles/driver-health/assessing-fitness-to-drive")],
 [M("Silver Book (Medical care of older persons)","https://www.racgp.org.au/clinical-resources/clinical-guidelines/key-racgp-guidelines/view-all-guidelines/silver-book","reference")]),
U("contextual",28,"Pain management","pain-management",
 "Persistent pain is a disease in its own right. Opioid harm taught Australia that biopsychosocial, function-first care is the only approach that works.",
 ["Assess pain biopsychosocially (function, mood, sleep, beliefs, context)",
  "Manage acute pain well (multimodal, short courses) to prevent chronicity; taper high-dose opioids with support",
  "Deliver interdisciplinary persistent pain care (programs, pacing, CBT) rather than escalating drugs"],
 "A 47-year-old on oxycodone 40 mg/day for chronic back pain asks for more. (CCE areas: data gathering - function, mood, aberrant behaviours; clinical management - explain hyperalgesia, taper plan, interdisciplinary program; communication - alliance without capitulation.)",
 ["Learn the opioid taper structure and the yellow-flag screen"],
 [G("eTG Analgesic/Palliative",ETG), G("Faculty of Pain Medicine","https://www.anzca.edu.au/faculty-of-pain-medicine")],
 [M("Local persistent pain programs list","https://www.aci.health.nsw.gov.au","org")]),
U("contextual",29,"Palliative care","palliative-care",
 "Most Australians die with diseases GPs manage. Good end-of-life care: symptom control, anticipatory prescribing, recognising dying, carer support and voluntary assisted dying literacy (QLD law since 2023).",
 ["Manage terminal symptoms: pain (1/6 breakthrough rule), dyspnoea, secretions, delirium, nausea - anticipatory SC sets",
  "Recognise the dying phase and communicate it honestly; coordinate home/RACF deaths",
  "Facilitate advance care planning and know QLD VAD law (eligibility, process, conscientious objection)"],
 "A 78-year-old with metastatic lung cancer at home is entering the dying phase; family anxious. (CCE areas: data gathering - symptoms, fears, supports; clinical management - anticipatory meds, care team, cessation of burdensome interventions; communication - what dying looks like, permission for family.)",
 ["Write the anticipatory drug set (drug/indication/dose) from memory weekly",
 "Read the QLD VAD eligibility summary once"],
 [G("eTG Palliative Care",ETG), G("CareSearch","https://www.caresearch.com.au"), G("QLD Health - VAD guidance","https://www.health.qld.gov.au/clinical-practice-guidelines/palliative-care/voluntary-assisted-dying")],
 [M("Palliative Care Australia","https://palliativecareaustralia.org.au","org")]),
U("contextual",30,"Pregnancy and reproductive health","pregnancy-and-reproductive-health",
 "GPs do most antenatal and postnatal care: booking, routine screening, shared care, and the urgent triage points (ectopic, pre-eclampsia, reduced movements). Contraception and preconception counselling are core GP craft.",
 ["Deliver first antenatal visit care: dating, booking bloods (group/Ab, FBE, hep B, HIV, syphilis, urine MC&S), screening options discussion",
  "Recognise and refer: ectopic (pain/bleeding + positive test), pre-eclampsia red flags, reduced movements >26 weeks",
  "Provide full contraception counselling (LARC-first, UKMEC) and postnatal care (EPDS, feeding, contraception timing)"],
 "A 31-year-old at 9 weeks books in; partner from a high hepatitis B prevalence country. (CCE areas: data gathering - medical, family, exposure history; clinical management - booking tests + extra risk-based, folate/iodine, screening discussion; communication - informed choices.)",
 ["Write the booking blood list and the pre-eclampsia red flags cold",
 "Learn UKMEC categories for the top 5 contraceptives"],
 [G("Dept of Health - Pregnancy Care Guidelines","https://www.health.gov.au/our-work/clinical-practice-guidelines-pregnancy-care"), G("RANZCOG resources","https://ranzcog.edu.au"), G("SHQ (QLD) contraception resources","https://shq.org.au")],
 [M("Healthdirect pregnancy resources","https://www.healthdirect.gov.au","org")],
 []),
U("contextual",31,"Research in general practice","research-in-general-practice",
 "Evidence-literate GPs appraise studies, run audits and sometimes contribute research. Critical appraisal keeps practice honest; audit improves it.",
 ["Appraise studies: design, validity, size, applicability to your patients",
  "Run clinical audits (SNAP, prescribing, prevention) and act on findings",
  "Contribute data/answering surveys where useful; understand basic ethics processes"],
 "A drug rep presents a new trial showing '30% relative risk reduction'. (CCE areas: data gathering - absolute vs relative risk; clinical management - applicability to your population; professionalism - evidence over marketing.)",
 ["Do one critical appraisal exercise on a paper in your field per month",
  "Join or form a journal club"],
 [G("RACGP research unit","https://www.racgp.org.au")],
 [M("RACGP research and ethics resources","https://www.racgp.org.au","reference")],
 []),
U("contextual",32,"Respiratory health","respiratory-health",
 "Asthma and COPD alone affect ~2.5 million Australians; GPs manage both from diagnosis to palliative. SABA-only asthma treatment is now history; spirometry is mandatory for COPD diagnosis.",
 ["Diagnose asthma (variability + reversibility) and step to ICS-formoterol AIR therapy; written action plans; review reliever overuse",
  "Diagnose COPD with post-bronchodilator spirometry; deliver the only trajectory-changers (cessation, rehab) and step-up rules",
  "Triage haemoptysis (urgent CT + respiratory referral for smokers/mass) and investigate chronic cough systematically"],
 "A 24-year-old uses salbutamol 3-4 times weekly for months. (CCE areas: data gathering - control assessment, triggers, technique; clinical management - ICS-formoterol, action plan; communication - why the blue inhaler alone is no longer OK.)",
 ["Learn the AIR algorithm and the COPD step-up criteria (eosinophils >=0.3 / 2 exacerbations)",
 "Do spirometry interpretation drills weekly"],
 [G("Australian Asthma Handbook","https://www.nationalasthma.org.au/australian-asthma-handbook/complete-handbook"), G("COPD-X plan","https://copdx.org.au/copd-x-plan/"), G("Lung Foundation Australia","https://lungfoundation.com.au")],
 [M("Asthma Australia resources","https://asthma.org.au","org")]),
U("contextual",33,"Sexual health and gender diversity","sexual-health-and-gender-diversity",
 "STI rates are rising in Australia; GPs do most testing and all partner notification duties. Affirming care for LGBTQI+ patients measurably improves their health engagement.",
 ["Test by site and risk (NAATs, serology); treat per Australian STI guidelines and arrange partner notification",
  "Provide PrEP/PEP (PEP within 72 h) and HIV care linkage; screen opportunistically in every eligible patient",
  "Deliver gender-affirming, non-judgemental care; use chosen names/pronouns; know referral pathways"],
 "A 22-year-old asymptomatic man who has sex with men requests a check. (CCE areas: data gathering - sexual history without judgement; clinical management - site-specific NAATs + HIV/syphilis, PrEP discussion; communication - normalising, confidentiality.)",
 ["Memorise the site-by-site STI testing table",
 "Save the PEP hotline and PrEP guidelines link"],
 [G("Australian STI Management Guidelines","http://sti.guidelines.org.au/"), G("ASHM","https://ashm.org.au")],
 [M("PrEP guidelines (ASHM)","https://ashm.org.au","reference")]),
U("contextual",34,"Travel medicine","travel-medicine",
 "Pre-travel consults are risk assessments: destination-specific vaccines (typhoid, hep A, rabies, Japanese encephalitis), malaria chemoprophylaxis, and behaviour advice. Returned travellers are a different consult.",
 ["Assess by itinerary: vaccines by destination, malaria risk by region and season, dengue/Zika advice",
  "Prescribe chemoprophylaxis correctly (drug, start-before, side-effects) and give bite-avoidance advice",
  "Manage the returned traveller: fever same-day (malaria), persistent diarrhoea, eosinophilia"],
 "A family with two children is trekking in rural Thailand for 3 weeks. (CCE areas: data gathering - itinerary, activities, duration, pregnancy/medical; clinical management - routine + travel vaccines, malaria assessment, bite avoidance; communication - risk without alarm.)",
 ["Build a region quick-table for the 5 most common destinations your patients visit"],
 [G("CDC Yellow Book","https://wwwnc.cdc.gov/travel"), G("WHO travel health","https://www.who.int/health-topics/travel-and-health")],
 [M("Travelvax Australia","https://www.travelvax.com.au","org")]),
U("contextual",35,"Women's health","womens-health",
 "Cervical screening (self-collection era), menopause care, HMB, PCOS and breast symptoms are daily GP work. Individualised, evidence-based care - especially around MHT - is the standard.",
 ["Deliver cervical screening including self-collection choice; manage results per pathways (LBC after non-16/18 HPV)",
  "Manage menopause: individualised MHT risk-benefit (timing hypothesis), non-hormonal options, GSM treatments",
  "Assess breast lumps urgently (triple assessment pathway) and manage HMB/PCOS systematically"],
 "A 49-year-old with perimenopausal symptoms and a uterus asks about 'natural' hormones. (CCE areas: data gathering - symptom inventory, risk factors; clinical management - MHT options/risks, compounded hormones caution; communication - shared decision, contraception still needed.)",
 ["Learn the cervical screening result pathway and MHT contraindications",
 "Read the menopause society statement on compounded bioidenticals once"],
 [G("National Cervical Screening Program","https://screening.cancer.org.au/cervical/"), G("Australasian Menopause Society","https://www.menopause.org.au"), G("BreastScreen Australia","https://www.breastscreen.org.au")],
 [M("Cancer Council breast resources","https://www.cancer.org.au","org")],
 []),
]

# validate uniqueness and count
names = [u["name"] for u in units]
assert len(names) == len(set(names)), "duplicate unit names"
core = [u for u in units if u["type"]=="core"]; ctx = [u for u in units if u["type"]=="contextual"]
print(f"units: {len(units)} (core {len(core)}, contextual {len(ctx)})")

out = dict(units=units)
(D / "curriculum_v3.json").write_text(json.dumps(out, indent=1), encoding="utf-8")
print("wrote curriculum_v3.json")
