#!/usr/bin/env python
"""AKT batch 4: ~28 questions (infectious, immunisation, ATSI health, mental health, ethics, medication safety, emergency, practice systems)."""
import json, pathlib
D = pathlib.Path(__file__).parent / "data"

def q(topic, unit, stem, options, explanation, pearl=None, trap=None):
    return dict(topic=topic, unit=unit, stem=stem, options=options, answers=[0], explanation=explanation, pearl=pearl, trap=trap)

Q = [
q("Cellulitis", "Infectious diseases", "A 55-year-old woman has a 3-day spreading red hot swollen left calf, afebrile, no systemic upset, no portal visible. WCC normal. What is the MOST appropriate management?", ["Flucloxacillin 500 mg qid for 5-7 days with clear escalation advice","Amoxycillin-clavulanate for all cellulitis","IV antibiotics in the practice","Antifungal cream","No antibiotics - it is erysipelas"], "Non-severe cellulitis without systemic features: oral flucloxacillin (anti-staphylococcal penicillin) with a defined review; escalate for rapid spread, systemic signs or failed therapy.", "Red leg = flucloxacillin unless the story says otherwise.", "Broad-spectrum co-amoxiclav as the reflex choice."),
q("Bites", "Infectious diseases", "A 30-year-old was bitten on the hand by a dog 2 hours ago; puncture wounds, no tendon/neuro compromise, wound cleaned. What is the MOST appropriate management?", ["Amoxycillin-clavulanate prophylaxis, tetanus review, and wound care advice","Flucloxacillin","No antibiotics for all bites","Metronidazole alone","Suture the puncture wounds tightly"], "Animal bites (esp. hands): prophylaxis with amoxycillin-clavulanate (Pasteurella cover) plus tetanus check; puncture wounds are not closed primarily.", "Hand bites get antibiotics; punctures stay open.", "Primary closure of a puncture wound."),
q("Q fever", "Infectious diseases", "A 46-year-old abattoir worker in rural Queensland has 5 days of high fever, severe headache and myalgia with a mild dry cough. What is the MOST likely diagnosis to consider and the treatment?", ["Q fever - doxycycline, and notify","Influenza - oseltamivir","Malaria","Legionella","Kawasaki disease"], "Q fever (Coxiella burnetii) in QLD: abattoir/farm exposure, fever + headache ± atypical pneumonia; treat with doxycycline; it is notifiable, and vaccination exists for at-risk workers.", "QLD + abattoir + fever + headache = Q fever.", "Missing the occupational history that makes the diagnosis."),
q("Malaria", "Infectious diseases", "A 28-year-old returns from Papua New Guinea with 2 days of high fever and rigors. What is the MOST appropriate action?", ["Same-day hospital assessment with urgent malaria bloods (thick and thin films) - falciparum until excluded","Start empirical doxycycline at home","Reassure - it is a viral illness","Repeat films next week if unwell","Chloroquine at home"], "Fever in a returned traveller from a falciparum zone is a medical emergency: same-day films (or rapid antigen) and hospital-level management; falciparum malaria can kill within 48 hours.", "Returned + fever = malaria today, not Tuesday.", "Waiting for the third-day fever pattern."),
q("Tuberculosis", "Infectious diseases", "A 35-year-old arrived from the Philippines 3 months ago with 6 weeks of cough, night sweats and 5 kg weight loss. What is the MOST appropriate initial investigations?", ["Chest X-ray and sputum (3 specimens) for AFB microscopy and culture, plus notify public health","Serology for TB","Trial of antibiotics","CT abdomen","Mantoux test alone"], "Suspected pulmonary TB: CXR + sputum for acid-fast bacilli (3 specimens) and cultures; TB is notifiable and public health manages contacts; serology is not a TB test.", "Cough + weight loss + migration from a high-prevalence country = TB screen.", "Empirical antibiotics erasing the diagnostic yield."),
q("Influenza vaccination", "Infectious diseases", "A 35-year-old at 30 weeks gestation asks about influenza vaccination. What is the MOST appropriate advice?", ["Influenza vaccination is recommended and funded at any stage of pregnancy","Wait until after delivery","Contraindicated in the third trimester","Only the partner needs vaccination","Half dose only"], "Pregnant women are a funded priority group for influenza vaccination at any trimester (and pertussis from 20-32 weeks): maternal immunisation protects mother and neonate.", "Pregnant = funded flu vaccine, any stage.", "Deferring the vaccine to 'after the baby comes'."),
q("Pertussis vaccination", "Infectious diseases", "A woman at 28 weeks gestation asks about pertussis protection for the baby. What is the MOST appropriate advice?", ["She should receive dTpa ideally between 20 and 32 weeks of every pregnancy","Only the first pregnancy needs vaccination","Wait until after birth","The baby is protected by maternal antibodies alone until vaccination at 2 months","Grandparents cannot be vaccinated"], "dTpa in every pregnancy at 20-32 weeks maximises placental antibody transfer; partners and household contacts are also recommended (cocooning).", "Every pregnancy, 20-32 weeks, no exceptions.", "One-time vaccination for a lifetime of pregnancies."),
q("Vaccine contraindications", "Infectious diseases", "Which of the following is a TRUE contraindication to a live attenuated vaccine (e.g., MMR)?", ["Significant immunosuppression or pregnancy","Mild coryza","Current antibiotics","Family history of adverse events","Egg allergy (for MMR in modern practice)"], "Live vaccines (MMR, varicella, zoster live, yellow fever) are contraindicated in pregnancy and significant immunosuppression; minor illness, antibiotics, egg allergy (MMR) are not.", "Live vaccine + immunosuppression or pregnancy = the real contraindication.", "Deferring vaccination for a runny nose."),
q("Vaccine error", "Infectious diseases", "A nurse gives an MMR vaccine subcutaneously instead of intramuscularly. What is the MOST appropriate action?", ["Record the error, report to the vaccination program/pharmacovigilance; the dose does NOT need repeating for route deviation alone","Repeat the dose immediately","Discard all records","No documentation needed","Referral to ED"], "Vaccine administration errors: document, report (state program), assess - most route errors are not repeated doses; the Australian Immunisation Handbook has a vaccine error table.", "Document and report - do not reflexively re-vaccinate.", "Silent errors that corrupt immunisation records."),
q("Immunisation catch-up", "Infectious diseases", "A 5-year-old newly arrived child has no documented vaccines. What is the MOST appropriate approach?", ["Construct a catch-up schedule using the Handbook rules - valid doses count, spacing rules apply, and record all on the AIR","Restart every vaccine course from zero","One dose of everything today","No catch-up needed if the child is well","Serology for every antigen first"], "Catch-up: use documented doses where valid, apply minimum spacing/intervals per the Handbook, catch up the essential antigens promptly, and record everything on the AIR.", "Documented doses count; spacing rules are the law of catch-up.", "Restarting all courses - unnecessary over-vaccination."),
q("Aboriginal health checks", "Aboriginal and Torres Strait Islander health", "Which is TRUE about health checks for Aboriginal and Torres Strait Islander patients in general practice?", ["An annual comprehensive health check (MBS 715) is recommended, with follow-up of identified issues","Health checks are only for those over 50","A referral letter is sufficient","They must be done in hospital","They cannot be done alongside other visits"], "ATSI adults and children are eligible for annual comprehensive health assessments (MBS item 715) covering chronic disease, CVD risk from younger ages, and preventive care.", "Annual 715: the anchor of ATSI preventive care.", "Once-only or age-gated checks."),
q("ATSI cardiovascular risk", "Aboriginal and Torres Strait Islander health", "At what age should absolute CVD risk assessment typically begin for Aboriginal and Torres Strait Islander patients?", ["From 35 years (earlier than the general population's 45)","Only from 55","At 45 like everyone else","Only once diabetes develops","CVD risk tools do not apply"], "CVD risk assessment starts from age 35 for Aboriginal and Torres Strait Islander adults (vs 45 general population) - part of a younger, high-priority prevention strategy.", "Ten years earlier: 35 not 45.", "Same-age screening missing a decade of prevention."),
q("ATSI prescribing", "Aboriginal and Torres Strait Islander health", "A patient with close-the-gap eligibility needs a medication usually outside her budget. What is the MOST appropriate approach?", ["Check her CTG PBS entitlement so she receives the medicine with reduced or no co-payment","Prescribe a cheaper, less effective alternative","No medicines can be subsidised","Refer to ED for the prescription","Wait until hospital admission"], "Closing the Gap PBS co-payment arrangements give CTG-eligible patients access to most PBS medicines at reduced cost, supporting adherence and equity.", "The right drug at the right price: CTG scripts exist - use them.", "Therapeutic compromise for cost reasons."),
q("Anxiety disorders", "Mental health", "A 30-year-old has months of excessive worry, restlessness and sleep disturbance; she has been managing work but distress is growing. What is the MOST appropriate initial management?", ["Guided CBT-based psychological therapy (low-intensity CBT first-line for GAD)","Immediate long-term benzodiazepine","Start an SSRI at maximal dose","Antipsychotic","Reassurance with no follow-up"], "GAD: stepped care - psychological therapy (e.g., CBT) is first-line; medication if psychological is insufficient or severe; benzodiazepines only very short-term if at all.", "CBT before SSRI, SSRI before benzo.", "Long-term benzodiazepines for worry - dependence within weeks."),
q("Bipolar disorder", "Mental health", "A 26-year-old presents with 5 days of reduced sleep, racing thoughts, big spending and grandiosity. What is the MOST appropriate action?", ["Urgent mental health assessment - suspected mania (screen for bipolar before treating as depression)","Start an antidepressant today","Diagnose anxiety","Sleep hygiene handout","No action - youthful high spirits"], "Mania features (decreased need for sleep, grandiosity, spending) = urgent assessment; antidepressant monotherapy can flip mania. Diagnosis and mood-stabiliser decisions are specialist-led.", "Sleepless + grandiose + spending: mana until proven otherwise; never an SSRI alone.", "Antidepressants into an undiagnosed bipolar patient."),
q("Perinatal mental health", "Mental health", "At a 6-week postnatal check the EPDS is 15; the mother is tearful and the baby is well. What is the MOST appropriate management?", ["Assess risk, engage supports, refer for perinatal mental health care (psychological therapy; medication if moderate-severe with informed choice)","Reassure - baby blues only","Delay all treatment until weaning","Benzodiazepine for sleep","Separate mother and baby"], "EPDS ≥13 (or clinical concern): assess severity/risk, involve partner/family, perinatal-specific psychological therapy; SSRIs with an individualised risk-benefit discussion when needed (several are compatible with breastfeeding).", "Screen, then treat - postnatal depression is common, serious, treatable.", "Writing it off as baby blues at 6 weeks."),
q("Psychosis", "Mental health", "A 21-year-old is brought in by family: 3 weeks of social withdrawal, odd beliefs, and hearing voices. What is the MOST appropriate action?", ["Urgent mental health assessment (early psychosis pathway)","Antidepressant trial","Sleep study","Benign observation for a year","Antipsychotics started casually without assessment"], "First-episode psychosis: early assessment via a youth/early psychosis service improves outcomes; medication decisions belong with the assessing team.", "Duration and function decline matter: refer early psychosis.", "Writing it off as adolescence."),
q("Bulimia nervosa", "Mental health", "A 24-year-old has episodes of binge eating with self-induced vomiting twice weekly for 6 months, BMI 23. What is the MOST appropriate management?", ["Guided CBT for eating disorders with monitoring of electrolytes/dental damage","Admission for refeeding","Orlistat","Weight-loss program","No action - weight is normal"], "Bulimia: CBT-based eating-disorder therapy; monitor potassium (vomiting), dental erosion; admission is for medical instability; weight is often normal.", "Normal weight does not mean normal eating - check the K+.", "Refeeding protocols for a normal-BMI binge-purge patient."),
q("Grief", "Mental health", "A man whose wife died 4 weeks ago has weeping, poor sleep and reduced appetite but no suicidal ideation, and functions at work. What is the MOST appropriate response?", ["Normalise grief, support coping and social connection, review in a few weeks","Start an SSRI immediately","Bereavement is a disorder needing treatment","Refer to a psychiatrist","Admit"], "Acute grief is normal: validate, support, watch for depression or prolonged grief disorder developing (persistent impairment beyond ~6-12 months) - not medicated away in the first weeks.", "Grief is care, not a prescription.", "Medicalising the first weeks of loss."),
q("Confidentiality", "Ethics and law", "A 16-year-old asks for contraception, requesting her parents not be told; she is Gillick competent. What is the MOST appropriate approach?", ["Assess competence and manage confidentially within her best interests, with confidentiality limits explained","Refuse without parental consent","Inform her parents regardless","Only provide condoms","Refer to court"], "A competent minor can consent to treatment; maintain confidentiality unless risk of serious harm; document competence assessment (understanding, retention, weighing, communication).", "Competence is decision-specific and assessed, not assumed by age.", "Automatic parental notification breaching trust."),
q("Mandatory reporting QLD", "Ethics and law", "In Queensland, a doctor suspects significant harm risk to a child from physical abuse. What is the correct action?", ["Report the suspicion to Child Safety (mandatory for doctors) - suspicion, not proof, is the threshold","Only report if the child confirms abuse","Wait for absolute certainty","Tell the parents first","Refer to police only"], "QLD: doctors must report a reasonable suspicion of a child suffering, or at risk of, significant harm. Report to Child Safety; verbatim documentation; do not confront the family.", "Reasonable suspicion is the threshold, not proof.", "Certainty paralysis while risk persists."),
q("Medical certificate", "Ethics and law", "A patient asks for a backdated medical certificate for three days last week when he was unwell but did not attend. What is the MOST appropriate response?", ["Explain certificates must be accurate: you can only certify what you can verify or reasonably attest, and backdating is not acceptable","Provide it - patient honesty is assumed","Refuse and end the consultation","Issue for 7 days to be safe","Charge extra for the certificate"], "Certificates are legal documents; write only what is truthful and verifiable (a certificate can reflect your assessment of the illness period if clearly framed and honest, but not fabricated); backdating to deceive is improper.", "The certificate protects the truth, not the patient's roster.", "Kind-hearted backdating = fraud."),
q("AHPRA notifications", "Ethics and law", "You are treating a doctor for opioid dependence. Are you obliged to report them to AHPRA?", ["Generally no - treating practitioners have protection from the impairment mandatory-notification obligation, provided the patient is managed safely","Yes - all dependent doctors must be reported","Only if they work in the same practice","Yes, anonymously","Only if they agree"], "Mandatory notification for impairment generally does NOT apply to treating practitioners; the focus is on supporting treatment and safe practice; notification duties centre on risk to the public (e.g., practising while intoxicated, sexual misconduct, substantial departure).", "Treat the doctor as a patient - the notification rules are narrower than people fear.", "Reporting your own patient and destroying their treatment."),
q("Antibiotic allergy", "Medication safety", "A patient labelled 'penicillin allergy - rash as a child' needs flucloxacillin for cellulitis. What is the BEST approach?", ["Take a careful allergy history (reaction, timing, severity) - childhood rash alone often is not true allergy; consider delabelling pathways if low risk","Avoid all beta-lactams forever","Use vancomycin","Prescribe cephalexin without any history","Oral clindamycin for everyone"], "Most 'penicillin allergy' labels are childhood viral rashes: a structured history (what, when, how severe, immediate vs delayed) and direct antibiotic guidelines (with allergy tools/delabelling where appropriate) restore first-line therapy.", "The label is often wrong - take the history, then treat.", "Life-long broad-spectrum avoidance of a mislabel."),
q("Warfarin interactions", "Medication safety", "A patient on warfarin (INR stable) is prescribed a 5-day course of clarithromycin. What is the MOST appropriate action?", ["Warn about interaction, increase INR monitoring, and anticipate dose reduction","Nothing - antibiotics do not affect warfarin","Stop warfarin completely","Double the warfarin","Switch to aspirin"], "Clarithromycin inhibits warfarin metabolism (CYP3A4): anticipate INR rise, monitor early (day 3-4), reduce dose as needed; do not stop anticoagulation.", "New drug on warfarin = new INR check.", "Discovering the interaction via a bleeding event."),
q("Renal dosing", "Medication safety", "An 82-year-old man (eGFR 32) is prescribed doxycycline. Which statement is MOST correct?", ["Doxycycline generally requires no renal dose adjustment","Halve all doses in CKD","Doxycycline is contraindicated in CKD","Double the dose","Use IV only"], "Doxycycline (and azithromycin, rifampicin, linezolid) need no adjustment in renal impairment; commonly misadjusted drugs include DOACs, gabapentinoids, metformin, digoxin, allopurinol.", "Know the no-adjust list - and the must-adjust list.", "Blanket dose reduction assumptions causing undertreatment."),
q("Anaphylaxis", "Emergency medicine", "A patient develops urticaria, wheeze and hypotension 10 minutes after an antibiotic in your practice. What is the FIRST-line treatment?", ["Intramuscular adrenaline 0.5 mg (0.5 mL of 1:1000) into the outer thigh, repeated every 5 minutes as needed","IV hydrocortisone first","Oral antihistamine","IV adrenaline bolus","Watchful waiting for 30 minutes"], "Anaphylaxis: IM adrenaline into the anterolateral thigh is first-line, dose 0.5 mg adult (repeat 5-minute), lie flat, call 000; steroids and antihistamines are adjuncts that never come first.", "Adrenaline IM, thigh, now - everything else waits.", "Corticosteroid-first reflex, wasting the golden minutes."),
q("Asthma emergency", "Emergency medicine", "A 19-year-old with acute severe asthma can only speak in words, SpO2 90%, PEFR <50% predicted, and is getting tired. What is the MOST appropriate immediate action?", ["Call 000, continuous salbutamol nebs with ipratropium, systemic corticosteroids, sit upright","Send home with a new inhaler","Oral theophylline","Physiotherapy","Watch and wait 1 hour"], "Severe/life-threatening asthma (speech-in-words, exhaustion): 000, high-flow oxygen, continuous salbutamol + ipratropium, steroids early, prepare for escalation.", "Speech length is the severity meter.", "Underestimating the silent, tiring asthmatic."),
q("Ankle brachial index", "Emergency medicine", "A 60-year-old diabetic has a non-healing foot ulcer for 6 weeks. Pulses are barely palpable. What is the MOST appropriate initial vascular assessment?", ["Ankle-brachial index (with caution in calcified vessels) and urgent podiatry/diabetes foot-clinic referral","Compression bandaging","Hot water soaks","Gentle debridement by practice nurse alone","Nothing - diabetic ulcers heal slowly"], "Diabetic foot ulcer: assess perfusion (ABI ± toe pressures given calcification risk), offload, urgent multidisciplinary foot-clinic referral; compression without arterial assessment is dangerous.", "Healing needs perfusion, offloading, and the right clinic - all three.", "Compressing an ischaemic limb."),
q("Results follow-up", "General practice systems", "Which of the following reflects safe results-management practice in general practice?", ["Every result is reviewed, acknowledged and acted on by the ordering clinician with a tracking system","Reception communicates all results","No news is good news","Patients chase their own results","Results are filed without being seen"], "Safe results handling: all results tracked, viewed, and actioned by the clinician; critical results communicated directly; documentation of the plan and the notification.", "Tracking systems stop balls dropping.", "'No news is good news' - the classic systemic failure."),
q("Referral letters", "General practice systems", "What makes a referral letter clinically MOST useful?", ["A concise structured letter with the question, relevant history/examination/investigations, medication list and what the patient knows","Copying all notes verbatim","Length equals thoroughness","Sending without patient context","No question, just the diagnosis"], "Good referrals ask a clear question with a concise synthesis, and include meds, allergies, and the patient's understanding (which frames the reply and triage).", "Ask the question; the specialist will answer it.", "Ten pages of pasted notes and no actual question."),
]
print("batch4 count:", len(Q))
(D / "questions_akt_batch4.json").write_text(json.dumps(Q, ensure_ascii=False), encoding="utf-8")
print("wrote questions_akt_batch4.json")
