-- RACGP Study System - seed data (verified 2026-09-08/09)
-- Exam structure verified from racgp.org.au pages listed in exam_meta sources.

INSERT OR IGNORE INTO exam_meta (key, value, source_url, checked_date) VALUES
('exam_structure_summary','Three Fellowship exams: (1) AKT - 150 single best answer MCQs, application of knowledge in Australian GP context; (2) KFP - 70 multiple-selection questions (2-6 correct answers each), clinical reasoning; (3) CCE - 9 cases via Zoom (4 case discussions + 5 clinical encounters with role players), 15 min + 5 min reading per case. AKT and KFP must both be passed before CCE.','https://www.racgp.org.au/education/fracgp-exams/fellowship-exams/akt-and-kfp-exams','2026-09-08'),
('akt_detail','AKT: 150 single best answer questions. All questions equal value, no negative marking. Paper-based, bubble sheet, pens provided (no pencils/own pens). Delivered at 11am local time, 4 hours duration. Auto-marked; standard-set by practicing Fellows. Results as Pass/Fail + band F4-P4. Fee 2027.1: $2,868.','https://www.racgp.org.au/education/fracgp-exams/fellowship-exams/akt-and-kfp-exams','2026-09-08'),
('kfp_detail','KFP: 70 individual multiple-selection questions, each unrelated. 2-6 correct answers per question, number specified in the question. Multiple-selection format (bubble sheet) since 2025.2 (replaced free-text). Penalty: 0.35% deducted per extra bubble shaded over the requested number. 4 hours, paper-based. Each question = 1.43% of total mark. Fee 2027.1: $2,868.','https://www.racgp.org.au/education/fracgp-exams/fellowship-exams/akt-and-kfp-exams','2026-09-08'),
('cce_detail','CCE: 9 clinical cases, online via Zoom, over two consecutive weekends. 4 case discussions (talk through a case with examiner) + 5 clinical encounters (consult with a role player, examiner observes). Each case 15 minutes + 5 minutes reading time. Exam sessions up to 3 hours; allocated 4 weeks prior. Multiple examiners. Examiners are experienced GPs. Fee 2026.2: $5,866.','https://www.racgp.org.au/education/fracgp-exams/fellowship-exams/clinical-competency-exam','2026-09-08'),
('sequence_policy','AKT and KFP can be sat in any order. Both must be passed before sitting the CCE. You may enrol in all three in one semester; may enrol in CCE while awaiting AKT/KFP results (auto-withdrawn + refund if you fail AKT/KFP). Candidacy = 6 consecutive exam semesters over 3 years from first sitting.','https://www.racgp.org.au/education/registrars/fellowship-pathways/policy-framework/program-handbooks-and-guidance-documents/assessments-and-examinations-candidate-handbook/enrolling-in-the-exams','2026-09-08'),
('curriculum','RACGP 2022 Curriculum and Syllabus for Australian general practice (6th edition). 5 core domains + Aboriginal and Torres Strait Islander Health + Rural Health core units, 35 contextual units. Curriculum drives exam content.','https://www.racgp.org.au/education/education-providers/curriculum/curriculum-and-syllabus/home','2026-09-08'),
('exam_dates_2027_1','AKT Friday 15 January 2027; KFP Saturday 16 January 2027. Enrolments open 3 September 2026, close 1 October 2026. Results release typically ~6 weeks later. 2027.1 CCE expected June 2027 (dates being finalised, published before end of 2026).','https://www.racgp.org.au/education/fracgp-exams/sitting-your-exams/exam-dates-and-enrolments','2026-09-08'),
('exam_dates_2026_2','CCE 2026.2: Day 1 Sat 7/Sun 8 Nov 2026, Day 2 Sat 14/Sun 15 Nov 2026; enrolments closed 31 Aug 2026; results 16 Dec 2026.','https://www.racgp.org.au/education/fracgp-exams/sitting-your-exams/exam-dates-and-enrolments','2026-09-08'),
('passing_methodology','AKT/KFP: auto-marked, standard-set by practicing Fellows (internationally recognised methodology, modified Angoff per public reports). Pass marks NOT published. Results as Pass/Fail with band F4 (lowest) to P4 (highest); P1 first band above pass. CCE: multiple examiners, borderline-group method per candidate guidelines.','https://www.racgp.org.au/education/fracgp-exams/fellowship-exams/akt-and-kfp-exams','2026-09-08'),
('pass_rates','2026.1 cycle pass rates per RACGP public exam reports: AKT 80.6% overall, 88.1% first attempt; KFP 84.1% overall, 90.1% first attempt.','https://www.racgp.org.au/education/fracgp-exams/exam-results-and-next-steps/results-and-public-reports','2026-09-08'),
('eligibility','AGPT: satisfactory completion of education/training requirements for exam eligibility per training plan + 2 years FTE program time including all of GPT1 and GPT2 by AKT date. RACGP membership + current AHPRA registration required. (User context: PGY4 AGPT registrar, Metro South Health, Brisbane.)','https://peoplemedical.com.au/what-are-the-eligibility-requirements-to-sit-the-racgp-fellowship-exams','2026-09-08'),
('study_mix','Target study mix: 30-40% knowledge review, 60-70% active recall/questions/cases.','', '2026-09-08');

-- Fix the bad row above (url mis-split): overwrite exam_dates_2026_2 cleanly
INSERT INTO exam_meta (key, value, source_url, checked_date) VALUES ('exam_dates_2026_2','CCE 2026.2: Day 1 Sat 7/Sun 8 Nov 2026, Day 2 Sat 14/Sun 15 Nov 2026; enrolments closed 31 Aug 2026; results 16 Dec 2026.','https://www.racgp.org.au/education/fracgp-exams/sitting-your-exams/exam-dates-and-enrolments','2026-09-08') ON CONFLICT(key) DO UPDATE SET value=excluded.value, source_url=excluded.source_url, checked_date=excluded.checked_date;

INSERT OR IGNORE INTO settings (key, value) VALUES
('candidate','Dr Kangxian Lim - PGY4, AGPT registrar, Metro South Health, Brisbane QLD'),
('target_exams','AKT + KFP 2027.1 (15/16 Jan 2027), CCE 2027.1 (June 2027, expected)'),
('weekly_capacity_weekday_min','30'),
('weekly_capacity_weekend_hours','2-4'),
('phase','1 - Foundation');
